Repository antgroup/vsag, pull requests merged in 2024-12, with the labels that each got.

#147 update several minor in conjugate graph
  src/impl/conjugate_graph.cpp
  src/impl/conjugate_graph.h
  src/index/hnsw.cpp
  src/index/hnsw.h
  tests/fixtures/fixtures.cpp
  tests/fixtures/fixtures.h
  tests/test_index_old.cpp
  tests/test_multi_thread.cpp
Labels: kind/feature, size/L

#140 add resize for hgraph
  src/data_cell/graph_interface.h
  src/index/hgraph_index.cpp
  src/index/hgraph_index.h
  src/index/hgraph_zparameters.cpp
Labels: kind/improvement, size/S

#168 introduce some constants config for hgraph
  examples/cpp/simple_hgraph_sq8.cpp
  include/vsag/constants.h
  src/constants.cpp
  src/index/hgraph_index.cpp
  src/index/hgraph_zparameters.cpp
  src/inner_string_params.h
Labels: kind/improvement, size/S

#170 fix ci script bug
  .circleci/config.yml
  Makefile
  scripts/test_parallel_bg.sh
  src/index/hnsw.cpp
Labels: kind/improvement, size/M

#173 [skip ci]assign new reviewers
  .github/CODEOWNERS
Labels: kind/improvement, size/S

#155 introduce the IndexFeature for user
  include/vsag/index.h
  include/vsag/index_feature.h
Labels: kind/feature, size/M

#181 add general test for hgraph
  src/index/hgraph_index.cpp
  src/index/hgraph_index.h
  src/index/hgraph_zparameters.cpp
  src/stream_writer.h
  tests/fixtures/fixtures.cpp
  tests/fixtures/fixtures.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
Labels: kind/feature, size/L

#163 implement for hgraph_range
  src/index/hgraph_index.cpp
  src/index/hgraph_index.h
Labels: kind/improvement, size/L

#184 remove the buffer in stream-based deserialization
  src/index/hnsw.cpp
Labels: size/S

#177 fix illegal instruction on platform which has avx only
  src/simd/CMakeLists.txt
  src/simd/avx.cpp
  src/simd/avx512_test.cpp
  src/simd/avx_test.cpp
  src/simd/fp32_simd.h
  src/simd/fp32_simd_test.cpp
  src/simd/normalize.cpp
  src/simd/normalize.h
  src/simd/normalize_test.cpp
  src/simd/sq4_simd.h
  src/simd/sq4_uniform_simd.h
  src/simd/sq4_uniform_simd_test.cpp
  src/simd/sq8_simd.h
  src/simd/sq8_simd_test.cpp
  src/simd/sq8_uniform_simd.h
  src/simd/sq8_uniform_simd_test.cpp
Labels: kind/bug, size/L

#183 remove the buffer in stream-based deserialization
  src/index/hnsw.cpp
Labels: size/S

#186 rename Set to Get for simd
  src/simd/fp32_simd.cpp
  src/simd/normalize.cpp
  src/simd/sq4_simd.cpp
  src/simd/sq4_uniform_simd.cpp
  src/simd/sq8_simd.cpp
  src/simd/sq8_uniform_simd.cpp
Labels: kind/improvement, size/M

#187 clear ci output
  scripts/test_parallel_bg.sh
Labels: kind/improvement, size/S

#185 enable range_test for hgraph
  tests/test_hgraph.cpp
  tests/test_index.cpp
Labels: kind/improvement, size/XS

#182 fix bug when running ft "index search distance"
  extern/diskann/DiskANN/src/pq_flash_index.cpp
  src/algorithm/hnswlib/hnswalg.h
Labels: size/XS

#190 fix return labels error on hgraph
  src/index/hgraph_index.cpp
  tests/test_index.cpp
Labels: kind/bug, size/XS

#200 [skip ci] make the owner list shorter
  .github/CODEOWNERS
Labels: kind/improvement, size/S

#201 use option as default block_size of hgraph index
  src/index/hgraph_zparameters.cpp
  src/index/hgraph_zparameters.h
Labels: kind/improvement, size/S

#195 split hgraph_index to algo and index impl
  src/CMakeLists.txt
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/index/hgraph_index.cpp
  src/index/hgraph_index.h
Labels: kind/improvement, size/XXL

#158 move test_performance to tools
  CMakeLists.txt
  Makefile
  tests/CMakeLists.txt
  tools/CMakeLists.txt
  tools/README.md
  tools/eval_dataset.cpp
  tools/eval_dataset.h
  tools/test_performance.cpp
Labels: kind/improvement, size/XL, module/tools

#194 new method to manage resource in engine
  include/vsag/engine.h
  include/vsag/resource.h
  src/engine.cpp
  src/resource.cpp
  src/resource_owner_wrapper.h
  src/safe_allocator.h
Labels: kind/feature, size/L

#179 introduce github action for ci test asan
  .circleci/config.yml
  .github/workflows/asan_build_and_test.yml
  Makefile
  scripts/test_parallel_bg.sh
  src/quantization/sq8_uniform_quantizer.h
  src/simd/simd.cpp
  tests/test_hnsw.cpp
Labels: kind/improvement, size/L

#206 modify the data structure of VisitList for stack operations
  src/algorithm/hnswlib/visited_list_pool.h
  src/typing.h
Labels: size/XS

#202 hotfix for slow deserialization
  src/algorithm/hnswlib/block_manager.cpp
  src/algorithm/hnswlib/block_manager.h
  src/algorithm/hnswlib/hnswalg.h
  src/algorithm/hnswlib/stream_reader.cpp
  src/algorithm/hnswlib/stream_reader.h
  src/algorithm/hnswlib/stream_writer.cpp
  src/algorithm/hnswlib/stream_writer.h
  tests/test_index.cpp
Labels: size/L

#199 introduce feature list
  include/vsag/index.h
  include/vsag/index_feature.h
  src/index_feature_list.cpp
  src/index_feature_list.h
  src/index_feature_list_test.cpp
Labels: kind/feature, size/L

#207 [bugfix] fix hgraph concurrent build & continue add problem
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/data_cell/graph_datacell.h
  src/data_cell/graph_interface.h
  src/data_cell/sparse_graph_datacell.cpp
  src/data_cell/sparse_graph_datacell.h
  src/index/hgraph_zparameters.cpp
  tests/test_hgraph.cpp
Labels: kind/bug, size/M

#210 introduce feature for hgraph
  include/vsag/index_feature.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/data_cell/flatten_datacell.h
  src/data_cell/flatten_interface.h
  src/index/hgraph_index.h
  src/index_feature_list.cpp
  src/index_feature_list.h
  src/inner_string_params.h
  src/quantization/fp32_quantizer.h
  src/quantization/quantizer.h
  src/quantization/sq4_quantizer.h
  src/quantization/sq4_uniform_quantizer.h
  src/quantization/sq8_quantizer.h
  src/quantization/sq8_uniform_quantizer.h
Labels: kind/feature, size/L

#215 add the latest paper reference
  README.md
Labels: size/S

#217 solve the asan ci's omp compile problem
  .github/workflows/asan_build_and_test.yml
Labels: kind/improvement, size/XS

#224 use getExternalLabel instead getExternalLabeLp
  src/algorithm/hnswlib/hnswalg.cpp
Labels: kind/improvement, size/XS

#218 reduce the index expansion of the initial state
  src/algorithm/hnswlib/hnswalg.cpp
Labels: size/XS

#223 improve for hgraph resize
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
Labels: kind/improvement, size/S

#212 remove the excess locks
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
Labels: kind/improvement, size/S

#167 define the interface for the "pyramid"
  examples/cpp/simple_pyramid.cpp
  include/vsag/constants.h
  include/vsag/dataset.h
  src/constants.cpp
  src/dataset_impl.h
  src/index/pyramid.cpp
  src/index/pyramid.h
Labels: size/L

#229 fix the memory leak issue in VisitListPool allocation
  include/vsag/allocator.h
Labels: kind/bug, size/XS

#226 introduce more hgraph param to config by user
  include/vsag/constants.h
  src/constants.cpp
  src/index/hgraph_zparameters.cpp
Labels: kind/improvement, size/XS

#235 [skip ci]add badges in README.md
  DEVELOPMENT.md
  README.md
Labels: kind/documentation, size/S

#198 fix the issue of high deserialization time
  src/stream_reader.cpp
  src/stream_reader.h
Labels: size/M

#236 add sq8uniform for hgraph
  src/data_cell/flatten_interface.cpp
  src/index/hgraph_zparameters.cpp
  src/quantization/sq8_uniform_quantizer.h
  tests/test_hgraph.cpp
Labels: kind/feature, size/M

#221 refactor hgraph_params to solve static value leak
  src/index/hgraph_zparameters.cpp
  src/index/hgraph_zparameters.h
Labels: kind/bug, kind/improvement, size/L

#237 use getExternalLabel in hnswalg_static
  src/algorithm/hnswlib/hnswalg_static.h
Labels: kind/improvement, size/XS

#209 implement of the engine and rewrite factory
  examples/cpp/CMakeLists.txt
  examples/cpp/example_engine.cpp
  include/vsag/engine.h
  include/vsag/resource.h
  include/vsag/vsag.h
  src/algorithm/hgraph.cpp
  src/data_cell/flatten_datacell.h
  src/data_cell/flatten_datacell_test.cpp
  src/data_cell/graph_datacell_test.cpp
  src/data_cell/graph_interface_test.cpp
  src/data_cell/sparse_graph_datacell.cpp
  src/data_cell/sparse_graph_datacell_test.cpp
  src/default_allocator.h
  src/engine.cpp
  src/factory/factory.cpp
  src/index/hgraph_index.cpp
  src/index/hgraph_index.h
  src/index/hnsw.cpp
  src/index/hnsw.h
  src/index/hnsw_test.cpp
  src/index/index_common_param.cpp
  src/index/index_common_param.h
  src/io/memory_block_io.h
  src/io/memory_block_io_test.cpp
  src/io/memory_io.h
  src/io/memory_io_test.cpp
  src/quantization/fp32_quantizer.h
  src/quantization/fp32_quantizer_test.cpp
  src/quantization/sq4_quantizer.h
  src/quantization/sq4_quantizer_test.cpp
  src/quantization/sq4_uniform_quantizer.h
  src/quantization/sq4_uniform_quantizer_test.cpp
  src/quantization/sq8_quantizer.h
  src/quantization/sq8_quantizer_test.cpp
  src/quantization/sq8_uniform_quantizer.h
  src/quantization/sq8_uniform_quantizer_test.cpp
  src/resource.cpp
  src/resource_owner_wrapper.h
  src/safe_allocator.h
  tests/test_engine.cpp
Labels: kind/feature, size/XL, version/0.12

#227 introduce new train method for sq
  src/quantization/scalar_quantization_trainer.cpp
  src/quantization/scalar_quantization_trainer.h
Labels: kind/improvement, size/M

#232 add concurrent search test for hnsw & hgraph
  tests/fixtures/thread_pool.h
  tests/test_hgraph.cpp
  tests/test_hnsw_new.cpp
  tests/test_index.cpp
  tests/test_index.h
  tests/test_multi_thread.cpp
Labels: kind/improvement, size/L

#233 add pyvsag package tool
  .gitignore
  CMakeLists.txt
  Makefile
  python/example.c
  python/pyvsag/__init__.py
  python/pyvsag/_version.py.in
  python/setup-requirements.txt
  python/setup.py
  python_bindings/binding.cpp
  scripts/build_pyvsag_multiple_version.sh
Labels: kind/feature, size/L, module/pyvsag, version/0.12

#247 [skip ci]use mergify to label pr
  .github/mergify.yml
Labels: kind/improvement, size/M

#242 add random allocator test for continue_add
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/data_cell/flatten_datacell.h
  src/index/hgraph_index.h
  src/io/memory_block_io.h
  tests/fixtures/random_allocator.h
  tests/test_hgraph.cpp
  tests/test_hnsw_new.cpp
  tests/test_index.cpp
  tests/test_index.h
  tests/test_random_allocator.cpp
Labels: kind/improvement, size/L

#241 fix bug on generate vector
  src/quantization/quantizer_test.h
  tests/fixtures/fixtures.cpp
  tests/fixtures/fixtures.h
Labels: kind/bug, size/S, version/0.12

#240 fix arm compile error
  .circleci/config.yml
  scripts/deps/install_deps_ubuntu.sh
  src/simd/CMakeLists.txt
  src/simd/avx.cpp
  src/simd/avx512.cpp
  src/simd/fp32_simd_test.cpp
  src/simd/normalize_test.cpp
  src/simd/sq4_simd_test.cpp
  src/simd/sq4_uniform_simd_test.cpp
  src/simd/sq8_simd.h
  src/simd/sq8_simd_test.cpp
  src/simd/sq8_uniform_simd_test.cpp
  src/simd/sse.cpp
  tests/CMakeLists.txt
Labels: kind/bug, size/L, version/0.12

#243 add "concurrent add test" for hnsw/hgraph
  include/vsag/index.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/index/hgraph_index.h
  src/index_feature_list.cpp
  tests/test_hgraph.cpp
  tests/test_hnsw_new.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/improvement, size/L, version/0.12

#251 introduce duplicate add for hgraph
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/impl/conjugate_graph.cpp
  src/impl/conjugate_graph.h
  src/index/hnsw.cpp
  src/typing.h
  tests/test_hgraph.cpp
  tests/test_hnsw_new.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/improvement, size/L, version/0.12

#196 support in-place update operation for hnsw
  include/vsag/index.h
  include/vsag/index_feature.h
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
  src/index/hnsw.cpp
  src/index/hnsw.h
  tests/test_hnsw_new.cpp
  tests/test_index.cpp
  tests/test_index.h
  tests/test_multi_thread.cpp
Labels: size/L, version/0.12

#258 refresh build cache for aarch
  .circleci/config.yml
  .circleci/fresh_ci_cache.commit
Labels: kind/bug, size/XS, version/0.12

#249 update the example of custom memory allocator
  examples/cpp/custom_memory_allocator.cpp
Labels: kind/improvement, size/M, version/0.12

#261 [skip ci]configure github automatically release notes generation
  .github/release.yml
Labels: kind/improvement, size/S, version/0.12

#263 fix the issue of memory misalignment during the HNSW assignment process
  src/algorithm/hnswlib/hnswalg.h
Labels: size/XS

#266 fix concurrent bug in update
  src/algorithm/hnswlib/hnswalg.cpp
Labels: kind/bug, size/XS

#268 fix tools compile error
  tools/CMakeLists.txt
Labels: kind/bug, size/XS

#257 add reorder for hgraph
  include/vsag/constants.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/constants.cpp
  src/index/hgraph_zparameters.cpp
  tests/fixtures/fixtures.cpp
  tests/fixtures/fixtures.h
  tests/test_hgraph.cpp
Labels: kind/improvement, size/L, version/0.13

#260 enable coverage test for github action
  .github/workflows/lcov.yml
  Makefile
  scripts/check_cov.sh
  scripts/collect_cpp_coverage.sh
  scripts/gcov_for_clang.sh
Labels: kind/improvement, size/L

#283 [skip ci]update readme
  README.md
  docs/banner.svg
Labels: kind/documentation, size/L

#285 disable asan for coverage test
  Makefile
  scripts/collect_cpp_coverage.sh
Labels: kind/improvement, size/S

#282 introduce memory estimate for hgraph
  include/vsag/index.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/index/hgraph_index.h
Labels: kind/feature, size/M
