Repository antgroup/vsag, pull requests merged in 2024-09, with the labels that each got.

#22 add star history in README.md
  README.md
Labels: documentation

#32 fix macro typo in unittest
  src/default_allocator_test.cpp
  src/index/hnsw.cpp
  src/index/hnsw.h
Labels: kind/improvement

#25 add some basic structure for quantizer, io and simd operators
  CMakeLists.txt
  extern/diskann/DiskANN/include/ann_exception.h
  src/algorithm/hnswlib/algorithm_interface.h
  src/io/basic_io.h
  src/io/file_aio.h
  src/io/memory_io.h
  src/io/memory_io_test.cpp
  src/metric_type.h
  src/quantization/fp32_quantizer.h
  src/quantization/fp32_quantizer_test.cpp
  src/quantization/quantizer.h
  src/quantization/quantizer_test.h
  src/simd/CMakeLists.txt
  src/simd/avx.cpp
  src/simd/avx512.cpp
  src/simd/fp32_simd.h
  src/simd/fp32_simd_test.cpp
  src/simd/generic.cpp
  src/simd/simd.cpp
  src/simd/simd.h
  src/simd/sse.cpp
  src/simd/sse_test.cpp
Labels: kind/improvement

#36 make openblas always run with single thread
  extern/openblas/openblas.cmake
Labels: kind/improvement

#38 remove redundant judgments during the HNSW search process
  src/algorithm/hnswlib/hnswalg.cpp
Labels: kind/improvement

#43 fix compile issue on arm
  src/simd/fp32_simd_test.cpp
  src/simd/sq8_simd_test.cpp
Labels: kind/bug

#37 add data cell structure, flatten as example
  src/CMakeLists.txt
  src/data_cell/flatten_datacell.h
  src/data_cell/flatten_datacell_test.cpp
  src/data_cell/flatten_interface.h
  src/io/basic_io.h
  src/io/memory_io.h
  src/quantization/computer.h
  src/quantization/fp32_quantizer.h
  src/quantization/fp32_quantizer_test.cpp
  src/quantization/quantizer.h
  src/quantization/quantizer_test.h
  src/quantization/sq8_quantizer.h
  src/quantization/sq8_quantizer_test.cpp
  src/simd/generic.cpp
Labels: kind/feature

#46 change the memory allocator of the HNSW in stl to a custom memory allocator
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
  src/data_cell/flatten_datacell.h
  src/default_allocator.h
  src/utils.h
Labels: kind/improvement, size/L

#50 fix illegal instruction issue on cpu without avx
  extern/diskann/diskann.cmake
Labels: kind/bug, size/XS
