Repository antgroup/vsag, pull requests merged in 2024-11, with the labels that each got.

#94 use parallel for ci_test
  .circleci/config.yml
  Makefile
  scripts/test_asan_bg.sh
Labels: kind/improvement, size/M

#81 support filter in test performance
  tests/performance/test_performance.cpp
Labels: kind/improvement, size/S, module/tools

#102 chore: compile example only when required
  CMakeLists.txt
  README.md
  examples/cpp/simple_hnsw.cpp
Labels: kind/improvement, size/M

#101 introduce cosine for quantizations
  scripts/test_asan_bg.sh
  src/quantization/fp32_quantizer.h
  src/quantization/fp32_quantizer_test.cpp
  src/quantization/quantizer_test.h
  src/quantization/sq4_quantizer.h
  src/quantization/sq4_quantizer_test.cpp
  src/quantization/sq4_uniform_quantizer_test.cpp
  src/quantization/sq8_quantizer.h
  src/quantization/sq8_quantizer_test.cpp
  src/simd/avx.cpp
  src/simd/avx512.cpp
  src/simd/fp32_simd_test.cpp
  src/simd/generic.cpp
  src/simd/normalize.h
  src/simd/normalize_test.cpp
  src/simd/sq4_simd_test.cpp
  src/simd/sq4_uniform_simd_test.cpp
  src/simd/sq8_simd_test.cpp
  src/simd/sse.cpp
  tests/fixtures/fixtures.cpp
Labels: kind/feature, size/L

#109 move common params check to class IndexCommonParam
  src/index/diskann_zparameters.cpp
  src/index/hnsw_zparameters.cpp
  src/index/index_common_param.cpp
  src/index/index_common_param.h
Labels: kind/improvement, size/L

#107 fix allocator lifetime issue
  src/default_allocator.h
  src/index/hnsw.cpp
  src/safe_allocator.h
Labels: kind/bug, size/S

#100 add basic index test
  tests/fixtures/fixtures.cpp
  tests/fixtures/fixtures.h
  tests/fixtures/test_dataset.h
  tests/test_diskann.cpp
  tests/test_hnsw_new.cpp
  tests/test_index.cpp
  tests/test_index.h
  tests/test_index_old.cpp
Labels: kind/improvement, size/XXL

#111 add hgraph param
  include/vsag/constants.h
  src/constants.cpp
  src/data_cell/flatten_interface.cpp
  src/data_cell/graph_interface.h
  src/index/hgraph_zparameters.cpp
  src/index/hgraph_zparameters.h
  src/index/hgraph_zparameters_test.cpp
  src/inner_string_params.h
  src/io/memory_block_io.h
  src/utils.cpp
  src/utils.h
Labels: kind/feature, size/L

#115 [skip ci]add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: kind/documentation, size/L

#119 fix test_performance
  tests/performance/test_performance.cpp
Labels: kind/improvement, size/XS

#118 fix test_asan_bg for unittest
  scripts/test_asan_bg.sh
  tests/fixtures/fixtures.h
  tests/test_index_old.cpp
Labels: kind/improvement, size/S

#113 optimize the simd operator
  src/simd/CMakeLists.txt
  src/simd/fp32_simd.cpp
  src/simd/fp32_simd.h
  src/simd/simd.h
  src/simd/simd_status.h
  src/simd/sq4_simd.cpp
  src/simd/sq4_simd.h
  src/simd/sq4_uniform_simd.cpp
  src/simd/sq4_uniform_simd.h
  src/simd/sq8_simd.cpp
  src/simd/sq8_simd.h
Labels: kind/improvement, size/XL, module/simd

#120 [skip ci] add doc for hgraph
  docs/hgraph_params.md
Labels: kind/documentation, size/M

#114 introduce hgraph
  src/data_cell/flatten_datacell.h
  src/data_cell/graph_datacell.h
  src/factory/factory.cpp
  src/index/hgraph_index.cpp
  src/index/hgraph_index.h
  src/index/hgraph_index_test.cpp
  src/index/hgraph_zparameters.cpp
  src/stream_writer.cpp
  src/stream_writer.h
Labels: kind/feature, size/XXL

#127 fix compile error in clang17
  src/data_cell/graph_datacell_test.cpp
  src/data_cell/sparse_graph_datacell_test.cpp
  tests/test_hnsw_new.cpp
Labels: kind/bug, size/S

#128 remove the dependency on gfortran during the MKL compilation process
  extern/diskann/diskann.cmake
  extern/mkl/mkl.cmake
Labels: size/XS

#124 increase third-party download time limit to fix occasional timeout
  extern/boost/boost.cmake
  extern/roaringbitmap/roaringbitmap.cmake
Labels: kind/improvement, size/XS

#129 simple example for hgraph
  examples/cpp/CMakeLists.txt
  examples/cpp/simple_hgraph_sq8.cpp
Labels: kind/improvement, size/M

#117 implement sq4&sq4_uniform for flatten_datacell
  src/data_cell/flatten_interface.cpp
  src/inner_string_params.h
  src/quantization/quantizer_headers.h
  src/quantization/quantizer_test.h
  src/quantization/sq4_quantizer.h
  src/quantization/sq4_quantizer_test.cpp
  src/quantization/sq4_uniform_quantizer.h
  src/quantization/sq4_uniform_quantizer_test.cpp
Labels: kind/feature, size/L

#130 add more ci resources and utilization
  .circleci/config.yml
  scripts/test_asan_bg.sh
Labels: kind/improvement, size/M

#134 alias some shared_ptr
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg_static.h
  src/algorithm/hnswlib/visited_list_pool.h
  src/data_cell/flatten_datacell.h
  src/data_cell/flatten_interface.h
  src/index/hgraph_index.cpp
  src/index/hgraph_index.h
  src/quantization/computer.h
Labels: kind/improvement, size/M

#139 update DEVELOPMENT.md
  DEVELOPMENT.md
  Makefile
Labels: kind/documentation, size/M

#133 alias nlohmann::json to JsonType
  src/factory/factory.cpp
  src/factory/factory_test.cpp
  src/footer.cpp
  src/footer.h
  src/impl/conjugate_graph.h
  src/impl/conjugate_graph_test.cpp
  src/index/diskann.cpp
  src/index/diskann.h
  src/index/diskann_test.cpp
  src/index/diskann_zparameters.cpp
  src/index/hgraph_index.cpp
  src/index/hgraph_index.h
  src/index/hgraph_index_test.cpp
  src/index/hgraph_zparameters.cpp
  src/index/hgraph_zparameters.h
  src/index/hnsw.cpp
  src/index/hnsw_test.cpp
  src/index/hnsw_zparameters.cpp
  src/index/index_common_param.cpp
  src/index/index_common_param.h
  src/io/memory_block_io.h
  src/io/memory_io.h
  src/quantization/fp32_quantizer.h
  src/quantization/sq4_quantizer.h
  src/quantization/sq4_uniform_quantizer.h
  src/quantization/sq8_quantizer.h
Labels: kind/improvement, size/L

#131 add new constants value: HGRAPH_GRAPH_MAX_DEGREE
  include/vsag/constants.h
  src/constants.cpp
  src/index/hgraph_zparameters.cpp
  src/index/hgraph_zparameters.h
Labels: kind/improvement, size/M

#98 support cosine in diskann
  extern/diskann/DiskANN/include/disk_utils.h
  extern/diskann/DiskANN/include/in_mem_data_store.h
  extern/diskann/DiskANN/src/disk_utils.cpp
  extern/diskann/DiskANN/src/in_mem_data_store.cpp
  extern/diskann/DiskANN/src/index.cpp
  extern/diskann/DiskANN/src/pq.cpp
  extern/diskann/DiskANN/src/pq_flash_index.cpp
  src/index/diskann.cpp
  src/index/diskann_zparameters.cpp
  tests/test_index_old.cpp
Labels: kind/feature, size/L

#142 add error redirect to log file for CI
  scripts/test_asan_bg.sh
Labels: kind/improvement, size/S

#146 avoiding test asan's nullptr memcpy&memcmp error
  src/data_cell/graph_interface_test.cpp
  tests/fixtures/fixtures.cpp
Labels: kind/improvement, size/XS

#145 split allocator_wrapper and default Allocator
  src/allocator_wrapper.h
  src/data_cell/graph_interface_test.cpp
  src/data_cell/sparse_graph_datacell_test.cpp
  src/dataset_impl_test.cpp
  src/default_allocator.h
  src/quantization/fp32_quantizer_test.cpp
  src/quantization/sq4_quantizer_test.cpp
  src/quantization/sq4_uniform_quantizer_test.cpp
  src/quantization/sq8_quantizer_test.cpp
  src/utils.h
Labels: kind/improvement, size/L

#151 enable sq4&sq4_uniform in HGraph
  src/index/hgraph_zparameters.cpp
Labels: kind/improvement, size/S

#149 use TEST_CASE_PERSISTENT_FIXTURE instead TEST_CASE_METHOD
  tests/test_hnsw_new.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/improvement, size/L

#132 delete unittest for hgraph
  src/index/hgraph_index.h
  src/index/hgraph_index_test.cpp
Labels: kind/improvement, size/L

#143 add range search for hgraph (only interface)
  src/index/hgraph_index.h
Labels: kind/feature, size/M

#153 speed up flatten by pass ref of shared_ptr
  src/data_cell/flatten_datacell.h
  src/data_cell/flatten_interface.h
Labels: kind/improvement, size/XS

#138 add invalid check on build and search for hgraph
  src/index/hgraph_index.cpp
Labels: kind/improvement, size/M

#144 move the Vector, UnorderMap, ... to typing.h
  src/stream_reader.h
  src/stream_writer.h
  src/typing.h
  src/utils.h
Labels: kind/improvement, size/M

#148 simplify the train of sq
  src/quantization/scalar_quantization_trainer.cpp
  src/quantization/scalar_quantization_trainer.h
  src/quantization/sq4_quantizer.h
  src/quantization/sq4_uniform_quantizer.h
  src/quantization/sq8_quantizer.h
Labels: kind/improvement, size/L

#135 enable fliter with exteral labels
  src/index/hgraph_index.cpp
  src/index/hgraph_index.h
  src/io/basic_io.h
  src/typing.h
Labels: kind/improvement, size/S

#137 fix memory leak for hnsw
  include/vsag/allocator.h
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
  src/algorithm/hnswlib/hnswalg_static.h
  src/algorithm/hnswlib/visited_list_pool.h
  src/index/hgraph_index.cpp
Labels: kind/bug, size/M

#160 add simd headers for sq8uniform
  src/simd/CMakeLists.txt
  src/simd/sq8_uniform_simd.cpp
  src/simd/sq8_uniform_simd.h
  tests/fixtures/fixtures.cpp
  tests/fixtures/fixtures.h
Labels: kind/improvement

#136 use shared lock for global mutex of hgraph
  src/index/hgraph_index.cpp
  src/index/hgraph_index.h
Labels: kind/improvement, size/M

#159 introduce third party argparse for tools
  CMakeLists.txt
  extern/argparse/argparse.cmake
Labels: kind/improvement

#156 reduce the number of I/O operations for HNSW during deserialization
  src/algorithm/hnswlib/algorithm_interface.h
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
  src/algorithm/hnswlib/hnswalg_static.h
  src/footer.cpp
  src/footer.h
  src/footer_test.cpp
  src/impl/conjugate_graph.cpp
  src/impl/conjugate_graph.h
  src/impl/conjugate_graph_test.cpp
  src/index/hnsw.cpp
  src/stream_reader.cpp
  src/stream_reader.h
Labels: kind/improvement

#161 sq8uniform simd implement
  src/simd/avx.cpp
  src/simd/avx512.cpp
  src/simd/generic.cpp
  src/simd/sq8_uniform_simd_test.cpp
  src/simd/sse.cpp
Labels: kind/feature

#165 trans hnsw to hgraph in search param parse
  examples/cpp/simple_hgraph_sq8.cpp
  src/index/hgraph_index.cpp
  src/index/hgraph_zparameters.cpp
  src/index/hgraph_zparameters.h
Labels: kind/improvement, size/M

#164 mark dataset test static for test index
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/improvement

#126 refactor the code for index parameter parsing
  CMakeLists.txt
  include/vsag/constants.h
  src/constants.cpp
  src/factory/factory.cpp
  src/index/diskann.cpp
  src/index/diskann.h
  src/index/diskann_test.cpp
  src/index/diskann_zparameters.cpp
  src/index/diskann_zparameters.h
  src/index/diskann_zparameters_test.cpp
  src/index/hgraph_zparameters.cpp
  src/index/hgraph_zparameters.h
  src/index/hnsw.cpp
  src/index/hnsw.h
  src/index/hnsw_test.cpp
  src/index/hnsw_zparameters.cpp
  src/index/hnsw_zparameters.h
  src/index/hnsw_zparameters_test.cpp
  src/index/index_commom_param_test.cpp
  src/index/index_common_param.cpp
  src/index/index_common_param.h
  src/parameter_check.cpp
  src/utils.h
  tests/test_hnsw_new.cpp
Labels: kind/improvement, size/XXL

#171 add boundary checks for data when parsing the conjugate graph
  src/impl/conjugate_graph.cpp
Labels: size/XS

#152 [skip ci]update python example
  .gitignore
  examples/python/example_hnsw.py
Labels: kind/improvement, size/S

#174 [skip ci]update README.md
  CONTRIBUTING.md
  README.md
Labels: kind/documentation, size/S
