Repository antgroup/vsag, pull requests merged in 2024-10, with the labels that each got.

#53 fix the issue of symbols defined in omp not found
  extern/mkl/mkl.cmake
  extern/roaringbitmap/roaringbitmap.cmake
Labels: kind/bug, size/S

#56 fix illegal memory access in SIMD
  src/quantization/fp32_quantizer.h
  src/quantization/sq8_quantizer.h
Labels: kind/bug, size/S

#57 fix hnsw memory leak in search
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
  src/algorithm/hnswlib/hnswalg_static.h
  src/algorithm/hnswlib/visited_list_pool.h
  tests/test_hnsw.cpp
Labels: kind/bug, size/M

#45 update README.md
  README.md
Labels: kind/documentation, size/S

#41 add sq4 quantizer and simd operators
  src/CMakeLists.txt
  src/quantization/quantizer.h
  src/quantization/sq4_quantizer.h
  src/quantization/sq4_quantizer_test.cpp
  src/quantization/sq4_uniform_quantizer.h
  src/quantization/sq4_uniform_quantizer_test.cpp
  src/simd/avx.cpp
  src/simd/avx512.cpp
  src/simd/generic.cpp
  src/simd/sq4_simd.h
  src/simd/sq4_simd_test.cpp
  src/simd/sq4_uniform_simd.h
  src/simd/sq4_uniform_simd_test.cpp
  src/simd/sse.cpp
  tests/fixtures/fixtures.cpp
  tests/fixtures/fixtures.h
Labels: kind/feature, size/XXL

#62 Add Graph Interface
  src/data_cell/graph_interface.h
Labels: kind/feature, size/L

#60 Support io direct read cross blocks
  src/data_cell/flatten_datacell.h
  src/data_cell/flatten_interface.h
  src/io/basic_io.h
  src/io/basic_io_test.h
  src/io/io_read_object.h
  src/io/memory_block_io.h
  src/io/memory_block_io_test.cpp
  src/io/memory_io.h
Labels: kind/feature, size/L

#61 Update quantization test & Add Serialize method
  src/quantization/fp32_quantizer.h
  src/quantization/fp32_quantizer_test.cpp
  src/quantization/quantizer.h
  src/quantization/quantizer_headers.h
  src/quantization/quantizer_test.h
  src/quantization/sq4_quantizer_test.cpp
  src/quantization/sq4_uniform_quantizer_test.cpp
  src/quantization/sq8_quantizer.h
  src/quantization/sq8_quantizer_test.cpp
  src/simd/generic.cpp
Labels: kind/feature, size/XL

#67 normalize the code by replacing abs with fabs
  tests/test_index.cpp
Labels: kind/improvement, size/XS

#33 support top-k search in test_performance
  tests/performance/README.md
  tests/performance/test_performance.cpp
Labels: kind/improvement, size/M

#72 clean code
  src/bitset_impl.cpp
  src/bitset_impl.h
  src/dataset_impl.cpp
  src/dataset_impl.h
  src/default_logger.cpp
  src/default_logger_test.cpp
  src/distances.cpp
  src/factory/factory.cpp
  src/footer.cpp
  src/footer_test.cpp
  src/options.cpp
  src/options_test.cpp
  src/safe_allocator.h
  src/utils.cpp
  src/utils.h
Labels: kind/improvement, size/M

#71 using typing.h to define LabelType and InnerIdType
  src/algorithm/hnswlib/algorithm_interface.cpp
  src/algorithm/hnswlib/algorithm_interface.h
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
  src/algorithm/hnswlib/hnswalg_static.h
  src/index/hnsw.cpp
  src/index/hnsw.h
  src/typing.h
Labels: kind/improvement, size/L

#69 [skip ci]add CODEOWNERS file
  .github/CODEOWNERS
Labels: kind/improvement, size/S

#63 increase the upper limit of the index parameter max_degree
  src/index/diskann_zparameters.cpp
  src/index/hnsw_zparameters.cpp
Labels: kind/improvement, size/S

#79 enable allocator for io
  src/io/memory_block_io.h
  src/io/memory_block_io_test.cpp
  src/io/memory_io.h
Labels: kind/feature, size/M, module/datacell

#78 make simd operators global (not only in simd/)
  src/simd/CMakeLists.txt
  src/simd/fp32_simd.h
  src/simd/generic.cpp
  src/simd/sq4_simd.h
  src/simd/sq4_uniform_simd.h
  src/simd/sq8_simd.h
Labels: kind/improvement, size/M, module/simd

#82 add DEVELOPMENT.md, who is using section
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
  docs/gist-960-euclidean_10_euclidean.png
  docs/weixin-qr.jpg
Labels: kind/documentation, size/L

#77 update simd operators for special dims
  src/io/memory_block_io_test.cpp
  src/quantization/sq4_quantizer_test.cpp
  src/quantization/sq4_uniform_quantizer_test.cpp
  src/quantization/sq8_quantizer_test.cpp
  src/simd/avx.cpp
  src/simd/sq8_simd_test.cpp
  src/simd/sse.cpp
Labels: kind/improvement, size/M, module/simd

#83 [skip ci]update README.md
  README.md
  docs/vsag_users.svg
Labels: kind/documentation, size/M

#85 bugfix: clang17 compile error
  src/base_filter_functor.h
Labels: kind/bug, size/S

#87 enable ccache in circleci
  .circleci/config.yml
Labels: kind/improvement, size/M

#93 add restore cache for main-branch-check
  .circleci/config.yml
Labels: kind/improvement, size/S

#84 add type check for io
  src/io/basic_io.h
  src/io/basic_io_test.cpp
  src/io/memory_block_io.h
  src/io/memory_io.h
Labels: kind/improvement, size/L

#80 enable allocator for quantizers
  src/data_cell/flatten_datacell_test.cpp
  src/quantization/computer.h
  src/quantization/fp32_quantizer.h
  src/quantization/fp32_quantizer_test.cpp
  src/quantization/quantizer.h
  src/quantization/quantizer_test.h
  src/quantization/sq4_quantizer.h
  src/quantization/sq4_quantizer_test.cpp
  src/quantization/sq4_uniform_quantizer.h
  src/quantization/sq4_uniform_quantizer_test.cpp
  src/quantization/sq8_quantizer.h
  src/quantization/sq8_quantizer_test.cpp
Labels: kind/feature, size/L, module/datacell

#89 fix compile issue in arm
  src/simd/sq4_simd.h
  src/simd/sq4_uniform_simd.h
Labels: size/XS

#91 fix(extern): remove duplicate mkl_core path
  extern/mkl/mkl.cmake
Labels: kind/improvement, size/XS

#95 enhance flatten_datacell functions
  src/data_cell/flatten_datacell.h
  src/data_cell/flatten_datacell_test.cpp
  src/data_cell/flatten_interface.cpp
  src/data_cell/flatten_interface.h
  src/data_cell/flatten_interface_test.cpp
  src/data_cell/flatten_interface_test.h
Labels: kind/improvement, size/L

#97 update temp_dir struct
  src/impl/conjugate_graph_test.cpp
  src/index/hnsw_test.cpp
  src/io/basic_io_test.cpp
  src/io/basic_io_test.h
  tests/fixtures/fixtures.h
  tests/test_index.cpp
  tests/test_vsag_ext.cpp
Labels: kind/improvement, size/L

#106 fix compile error
  src/data_cell/flatten_interface_test.cpp
Labels: size/XS

#103 support the use of different C++ standard libraries
  CMakeLists.txt
  Makefile
Labels: size/S
