Repository antgroup/vsag, pull requests merged in 2025-02, with the labels that each got.

#367 add a new filter interface provides hints like selection ratio
  examples/cpp/301_feature_filter.cpp
  include/vsag/filter.h
  include/vsag/index.h
Labels: kind/feature, size/L, version/0.13, module/api

#372 enable modernize-* checks in clang-tidy
  .clang-tidy
  src/algorithm/hgraph.cpp
  src/bitset_impl.cpp
  src/data_cell/flatten_datacell_parameter.cpp
  src/factory/factory.cpp
  src/impl/conjugate_graph.cpp
  src/impl/odescent_graph_builder.cpp
  src/index/brute_force.cpp
  src/index/diskann.cpp
  src/index/hnsw.cpp
  src/index/pyramid.cpp
  src/stream_writer.cpp
  src/utils.cpp
  src/utils.h
Labels: kind/improvement, size/L, version/0.13

#375 enable clang-analyzer-* checks in clang-tidy
  .clang-tidy
  src/factory/factory.cpp
  src/impl/basic_searcher.cpp
  src/index/diskann.cpp
  src/index/diskann_zparameters.h
  src/index/hnsw_zparameters.h
  src/io/memory_io_parameter.cpp
  src/safe_thread_pool.h
Labels: kind/improvement, size/M, version/0.13

#377 enable readability-* checks in clang-tidy
  .clang-tidy
  include/vsag/index.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/hgraph_parameter.cpp
  src/bitset_impl.cpp
  src/data_cell/flatten_interface.cpp
  src/data_cell/graph_interface.cpp
  src/data_cell/sparse_graph_datacell.cpp
  src/default_allocator.cpp
  src/default_thread_pool.cpp
  src/engine.cpp
  src/footer.cpp
  src/impl/basic_searcher.cpp
  src/impl/conjugate_graph.cpp
  src/impl/conjugate_graph.h
  src/impl/odescent_graph_builder.cpp
  src/impl/odescent_graph_builder.h
  src/index/brute_force.cpp
  src/index/diskann.cpp
  src/index/diskann.h
  src/index/diskann_zparameters.cpp
  src/index/hgraph_index_zparameters.cpp
  src/index/hnsw.cpp
  src/index/hnsw.h
  src/index/hnsw_zparameters.cpp
  src/index/index_common_param.cpp
  src/index/pyramid.cpp
  src/index_feature_list.cpp
  src/options.cpp
  src/parameter_generator.cpp
  src/stream_reader.cpp
  src/stream_writer.cpp
  src/vsag_ext.cpp
Labels: kind/improvement, size/L, version/0.13

#376 replace BaseFilter with UniqueFilter
  src/algorithm/hnswlib/algorithm_interface.cpp
  src/algorithm/hnswlib/algorithm_interface.h
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
  src/algorithm/hnswlib/hnswalg_static.h
  src/base_filter_functor.h
  src/index/hnsw.cpp
  src/index/hnsw.h
  tests/test_index_old.cpp
Labels: kind/improvement, size/L

#371 support build one point graph in odescent
  src/data_cell/sparse_graph_datacell.cpp
  src/impl/odescent_graph_builder.cpp
  src/impl/odescent_graph_builder_test.cpp
Labels: kind/improvement, size/M

#312 define the interface for merging indexes
  include/vsag/index.h
  include/vsag/index_features.h
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
  src/index/hnsw.cpp
  src/index/hnsw.h
  src/index/hnsw_test.cpp
  tests/test_hnsw_new.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/feature, size/L, version/0.14

#380 refactor tools directory
  .circleci/fresh_ci_cache.commit
  tools/CMakeLists.txt
  tools/README.md
  tools/eval/CMakeLists.txt
  tools/eval/eval_template.yaml
  tools/eval/main.cpp
  tools/test_performance/CMakeLists.txt
  tools/test_performance/README.md
  tools/test_performance/main.cpp
Labels: kind/improvement, size/L, version/0.13

#381 optimize the process of HNSW with high filtering ratio
  include/vsag/constants.h
  src/algorithm/hnswlib/algorithm_interface.h
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
  src/algorithm/hnswlib/hnswalg_static.h
  src/constants.cpp
  src/impl/odescent_graph_builder.cpp
  src/index/hnsw.cpp
  src/index/hnsw.h
  src/index/hnsw_zparameters.cpp
  src/index/hnsw_zparameters.h
  src/utils.h
  tests/fixtures/test_dataset.cpp
  tests/fixtures/test_dataset.h
  tests/fixtures/test_dataset_pool.cpp
  tests/fixtures/test_dataset_pool.h
  tests/test_hnsw_new.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/improvement, size/L, version/0.13

#355 introduce different kinds of heap
  src/CMakeLists.txt
  src/utils/distance_heap.h
  src/utils/distance_heap_test.cpp
  src/utils/memmove_heap.cpp
  src/utils/memmove_heap.h
  src/utils/standard_heap.cpp
  src/utils/standard_heap.h
Labels: kind/improvement, size/L, version/0.14

#362 introduce bucket datacell parameter
  src/data_cell/bucket_datacell_parameter.cpp
  src/data_cell/bucket_datacell_parameter.h
  src/data_cell/bucket_datacell_parameter_test.cpp
  src/inner_string_params.h
Labels: kind/feature, size/L, version/0.14

#359 add batch scan for quantizer compute
  src/quantization/computer.h
  src/quantization/fp32_quantizer.h
  src/quantization/quantizer.h
  src/quantization/quantizer_test.h
  src/quantization/scalar_quantization/sq4_quantizer.h
  src/quantization/scalar_quantization/sq4_uniform_quantizer.h
  src/quantization/scalar_quantization/sq8_quantizer.h
  src/quantization/scalar_quantization/sq8_uniform_quantizer.h
Labels: kind/feature, size/L, version/0.14

#383 fix template function specialization missing in hnsw
  src/index/hnsw.cpp
Labels: kind/bug, size/S, needs-cherry-pick-release-0.13

#391 fix template compile error
  src/utils/memmove_heap.cpp
  src/utils/memmove_heap.h
  src/utils/standard_heap.cpp
  src/utils/standard_heap.h
Labels: kind/bug, size/L

#386 [skip ci] refactor hgraph param doc
  docs/hgraph_params.md
Labels: kind/documentation, size/M, version/0.14

#392 [skip ci] Refresh example code link in README
  README.md
Labels: kind/documentation, size/XS

#357 unified all io serialize method
  src/byte_buffer.h
  src/data_cell/flatten_datacell.h
  src/io/basic_io.h
  src/io/basic_io_test.cpp
  src/io/memory_block_io.h
  src/io/memory_block_io_test.cpp
  src/io/memory_io.h
  src/io/memory_io_test.cpp
Labels: kind/improvement, size/L, version/0.14

#388 fix the incompatibility of v0.12 and v0.13 in HNSW
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
Labels: kind/bug, size/XS, needs-cherry-pick-release-0.13

#394 fix occasional failures of unittests caused by a high filter rate
  src/algorithm/hnswlib/hnswalg.cpp
  tests/test_hnsw_new.cpp
Labels: kind/bug, size/XS, needs-cherry-pick-release-0.13

#356 use trunc train for sq as default
  src/quantization/scalar_quantization/scalar_quantization_trainer.cpp
  src/quantization/scalar_quantization/scalar_quantization_trainer.h
Labels: kind/improvement, size/S, version/0.14

#396 add minor optimize on performance of hnswalg
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
Labels: kind/improvement, size/S, needs-cherry-pick-release-0.13

#397 optimize filter in HNSW by reduce CheckValid
  src/algorithm/hnswlib/hnswalg.cpp
Labels: kind/improvement, size/XS, needs-cherry-pick-release-0.13

#398 fix: Add missing <functional> header for readerset.h
  include/vsag/readerset.h
Labels: kind/bug, size/XS

#403 fix the incorrect assignment of prefetch_jump_code_size_
  src/algorithm/hnswlib/hnswalg.cpp
Labels: kind/bug, size/XS, needs-cherry-pick-release-0.13

#402 add libaio deps for ubuntu and centos
  scripts/deps/install_deps_centos.sh
  scripts/deps/install_deps_ubuntu.sh
Labels: kind/improvement, size/XS, version/0.14

#407 fix compiler issues when using clang make libcxx
  src/io/buffer_io_test.cpp
  src/io/memory_block_io.h
Labels: kind/bug, size/S, needs-cherry-pick-release-0.13

#412 add libaio-dev for dockerfile
  docker/Dockerfile.x86
Labels: kind/improvement, size/XS

#373 extract the pruning strategy from HGraph
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/impl/pruning_strategy.cpp
  src/impl/pruning_strategy.h
  src/lock_strategy.cpp
  src/lock_strategy.h
Labels: kind/improvement, size/L, version/0.14

#413 calculates recall by distances in eval_performance
  tools/eval/monitor/recall_monitor.cpp
  tools/eval/search_eval_case.cpp
Labels: kind/bug, size/S

#414 remove the brute-force strategy in filter search
  src/algorithm/hnswlib/hnswalg.cpp
Labels: kind/improvement, size/XS, needs-cherry-pick-release-0.13

#378 support filter & range for searcher
  src/algorithm/hnswlib/hnswalg.cpp
  src/data_cell/flatten_interface_test.cpp
  src/impl/basic_searcher.cpp
  src/impl/basic_searcher.h
  src/impl/basic_searcher_test.cpp
  src/utils/visited_list.h
Labels: kind/improvement, size/L, version/0.14

#415 introduce bf16 simd operators
  src/simd/CMakeLists.txt
  src/simd/avx.cpp
  src/simd/avx2.cpp
  src/simd/avx512.cpp
  src/simd/bf16_simd.cpp
  src/simd/bf16_simd.h
  src/simd/bf16_simd_test.cpp
  src/simd/generic.cpp
  src/simd/simd.h
  src/simd/sse.cpp
Labels: kind/feature, size/XL, version/0.14

#417 fix hgraph deserialize bug
  src/algorithm/hgraph.cpp
  tests/test_hgraph.cpp
Labels: kind/bug, size/XS

#406 support build graph from existing graph storage in ODescent
  src/impl/odescent_graph_builder.cpp
  src/impl/odescent_graph_builder.h
  src/impl/odescent_graph_builder_test.cpp
Labels: kind/improvement, size/L

#390 introduce an implement of kmeans-cluster
  src/impl/kmeans_cluster.cpp
  src/impl/kmeans_cluster.h
  src/impl/kmeans_cluster_test.cpp
Labels: kind/feature, size/L, version/0.14

#370 refactor pyramid from being index-based to datacell-based
  include/vsag/constants.h
  src/algorithm/hgraph.cpp
  src/base_filter_functor.h
  src/constants.cpp
  src/engine.cpp
  src/impl/basic_searcher.cpp
  src/impl/basic_searcher.h
  src/index/diskann.cpp
  src/index/diskann_zparameters.cpp
  src/index/pyramid.cpp
  src/index/pyramid.h
  src/index/pyramid_zparameters.cpp
  src/index/pyramid_zparameters.h
  src/index/pyramid_zparameters_test.cpp
  src/stream_reader.h
  src/stream_writer.h
  tests/test_index.cpp
  tests/test_pyramid.cpp
Labels: kind/improvement, size/XXL, module/testing, version/0.14

#325 add sparse dtype in dataset
  include/vsag/constants.h
  include/vsag/dataset.h
  src/constants.cpp
  src/dataset_impl.h
  src/dataset_impl_test.cpp
  tests/fixtures/fixtures.cpp
  tests/fixtures/fixtures.h
  tests/fixtures/test_dataset.cpp
Labels: kind/feature, size/L, module/testing, module/api, version/0.14

#429 use empty_index_set for serialize empty index
  src/algorithm/hgraph.cpp
  src/empty_index_binary_set.h
  src/index/diskann.cpp
  src/index/diskann.h
  src/index/hnsw.cpp
  src/index/hnsw.h
  src/index/pyramid.cpp
Labels: kind/improvement, size/L, version/0.14

#419 enable libaio for hgraph
  src/data_cell/flatten_datacell.h
  src/data_cell/flatten_interface.cpp
  src/io/async_io.h
  src/io/io_context.h
  src/io/io_headers.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
Labels: kind/feature, size/M, module/testing, version/0.14

#426 add random allocator test for pyramid
  src/index/pyramid.cpp
  src/index/pyramid.h
  src/io/async_io_test.cpp
  tests/test_index.cpp
  tests/test_index.h
  tests/test_pyramid.cpp
Labels: kind/improvement, size/M, module/testing

#435 fix sq4_uniform train bug on gist dataset
  include/vsag/constants.h
  src/constants.cpp
  src/index/hgraph_index_zparameters.cpp
  src/inner_string_params.h
  src/quantization/scalar_quantization/scalar_quantization_trainer.cpp
  src/quantization/scalar_quantization/scalar_quantization_trainer.h
  src/quantization/scalar_quantization/sq4_uniform_quantizer.h
  src/quantization/scalar_quantization/sq4_uniform_quantizer_parameter.cpp
  src/quantization/scalar_quantization/sq4_uniform_quantizer_parameter.h
  src/quantization/scalar_quantization/sq4_uniform_quantizer_parameter_test.cpp
Labels: kind/bug, size/M, version/0.14

#433 refactor utils
  src/CMakeLists.txt
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
  src/data_cell/sparse_graph_datacell.h
  src/factory.cpp
  src/factory_test.cpp
  src/impl/basic_searcher.h
  src/impl/odescent_graph_builder.cpp
  src/index/brute_force.cpp
  src/index/brute_force_parameter.cpp
  src/index/diskann.cpp
  src/index/diskann.h
  src/index/diskann_test.cpp
  src/index/hgraph_index_zparameters.cpp
  src/index/hnsw.cpp
  src/index/hnsw.h
  src/index/pyramid.cpp
  src/parameter_check.cpp
  src/parameter_generator.cpp
  src/utils.cpp
  src/utils/linear_congruential_generator.h
  src/utils/number.h
  src/utils/slow_task_timer.cpp
  src/utils/slow_task_timer.h
  src/utils/timer.cpp
  src/utils/timer.h
  src/utils/util_functions.cpp
  src/utils/util_functions.h
  src/utils/window_result_queue.cpp
  src/utils/window_result_queue.h
Labels: kind/improvement, size/XL, version/0.14

#430 introduce vsag exception to wrapper vsag::Error
  src/algorithm/hgraph.cpp
  src/common.h
  src/engine.cpp
  src/parameter_check.cpp
  src/utils/util_functions.h
  src/vsag_exception.h
Labels: kind/improvement, size/L, version/0.14

#428 implement automatic update of the total_count in the graph datacell
  src/algorithm/hgraph.cpp
  src/data_cell/graph_datacell.h
  src/data_cell/graph_interface.h
  src/data_cell/graph_interface_test.cpp
  src/data_cell/sparse_graph_datacell.cpp
  src/impl/odescent_graph_builder.cpp
  src/index/hnsw.cpp
Labels: kind/improvement, size/M

#420 add filter for eval_performance
  docs/dataset_format.md
  tools/eval/eval_dataset.cpp
  tools/eval/eval_dataset.h
  tools/eval/search_eval_case.cpp
Labels: kind/improvement, size/L, module/tools

#431 support rabitq quantizer basic funcs
  README.md
  src/inner_string_params.h
  src/quantization/CMakeLists.txt
  src/quantization/quantizer_test.h
  src/quantization/rabitq_quantization/rabitq_quantizer.h
  src/quantization/rabitq_quantization/rabitq_quantizer_parameter.cpp
  src/quantization/rabitq_quantization/rabitq_quantizer_parameter.h
  src/quantization/rabitq_quantization/rabitq_quantizer_parameter_test.cpp
  src/quantization/rabitq_quantization/rabitq_quantizer_test.cpp
  src/simd/CMakeLists.txt
  src/simd/generic.cpp
  src/simd/normalize.cpp
  src/simd/normalize.h
  src/simd/normalize_test.cpp
  src/simd/rabitq_simd.cpp
  src/simd/rabitq_simd.h
  src/simd/rabitq_simd_test.cpp
  tests/fixtures/fixtures.cpp
  tests/fixtures/fixtures.h
Labels: size/XL, module/simd, module/testing

#427 support add in pyramid
  src/algorithm/hgraph.h
  src/impl/pruning_strategy.cpp
  src/impl/pruning_strategy.h
  src/index/pyramid.cpp
  src/index/pyramid.h
  src/lock_strategy.h
  tests/test_pyramid.cpp
Labels: kind/feature, size/L, module/testing

#442 add arm asan build & test for github action
  .github/workflows/asan_build_and_test.yml
  .github/workflows/format.yml
Labels: kind/improvement, size/L, version/0.14

#448 remove arm ci on circle_ci
  .circleci/config.yml
Labels: kind/improvement, size/M, version/0.14

#445 Support random projection
  src/impl/random_orthogonal_matrix.cpp
  src/impl/random_orthogonal_matrix.h
  src/impl/random_orthogonal_matrix_test.cpp
Labels: size/L, module/simd

#424 update clang-tidy performance and readability options
  .clang-tidy
  src/impl/odescent_graph_builder.cpp
  src/impl/odescent_graph_builder.h
  src/impl/pruning_strategy.cpp
  src/impl/pruning_strategy.h
  src/index/diskann.cpp
  src/index/diskann.h
  src/index/diskann_zparameters.cpp
  src/index/diskann_zparameters.h
  src/index/hnsw.cpp
  src/index/hnsw.h
  src/index/hnsw_zparameters.cpp
  src/index/hnsw_zparameters.h
  src/index/pyramid.cpp
  src/index/pyramid.h
  src/stream_reader.cpp
  src/stream_reader.h
Labels: kind/improvement, size/M

#439 introduce index_impl layer
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/hgraph_parameter.h
  src/algorithm/inner_index_interface.cpp
  src/algorithm/inner_index_interface.h
  src/base_filter_functor.h
  src/common.h
  src/engine.cpp
  src/index/hgraph_index.cpp
  src/index/hgraph_index.h
  src/index/hgraph_index_zparameters.cpp
  src/index/hgraph_index_zparameters.h
  src/index/hnsw.h
  src/index/index_impl.h
  src/index/pyramid.cpp
  src/index/pyramid.h
  src/index_feature_list.h
  src/label_table.h
  src/parameter.h
  src/typing.h
  src/utils/util_functions.cpp
  src/utils/util_functions.h
Labels: kind/improvement, size/XXL, version/0.14

#444 support build one vector index in diskann
  extern/diskann/DiskANN/src/disk_utils.cpp
  extern/diskann/DiskANN/src/index.cpp
  extern/diskann/DiskANN/src/pq.cpp
  extern/diskann/DiskANN/src/pq_flash_index.cpp
  src/index/diskann.cpp
  src/index/diskann_test.cpp
  tests/test_random_index.cpp
Labels: kind/improvement, size/M, module/testing

#460 add const referance for shared_ptr
  src/algorithm/inner_index_interface.cpp
  src/algorithm/inner_index_interface.h
Labels: kind/improvement, size/S, version/0.14
