Repository antgroup/vsag, pull requests merged in 2025-09, with the labels that each got.

#1049 support in-place update in HGraph
  include/vsag/constants.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/hgraph_parameter.cpp
  src/algorithm/hgraph_parameter.h
  src/algorithm/inner_index_interface.cpp
  src/algorithm/inner_index_interface.h
  src/common.h
  src/constants.cpp
  src/data_cell/flatten_datacell.h
  src/data_cell/flatten_interface.h
  src/index/hnsw.cpp
  src/index/hnsw.h
  src/inner_string_params.h
  src/label_table.h
  src/utils/util_functions.cpp
  src/utils/util_functions.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
  tests/test_multi_thread.cpp
Labels: kind/improvement, size/XL, module/testing, version/0.17

#1102 [skip ci] docs(hgraph): refactor HGraph doc
  docs/hgraph.md
  docs/hgraph_params.md
Labels: kind/documentation, size/L, version/0.17

#1101 chore: add more tag for compatibility
  scripts/check_compatibility.sh
Labels: kind/improvement, size/XS, version/0.17

#1108 fix(sindi): fix redundant results in the return data
  src/algorithm/sindi/sindi.cpp
  src/data_cell/sparse_term_datacell.cpp
Labels: kind/bug, size/S, version/0.16, needs-cherry-pick-release-0.16

#1074 feat(dataset): support Append and DeepCopy methods in Dataset
  include/vsag/attribute.h
  include/vsag/dataset.h
  src/attr/attribute.cpp
  src/attr/attribute_test.cpp
  src/dataset_impl.cpp
  src/dataset_impl.h
  src/dataset_impl_test.cpp
  tests/fixtures/fixtures.cpp
  tests/fixtures/fixtures.h
  tests/fixtures/test_dataset.cpp
Labels: kind/feature, size/XL, module/testing, version/0.17

#1111 feat(sindi): support several interfaces
  include/vsag/index.h
  src/algorithm/inner_index_interface.h
  src/algorithm/sindi/sindi.cpp
  src/algorithm/sindi/sindi.h
  src/algorithm/sparse_index.cpp
  src/algorithm/sparse_index.h
  src/common.h
  src/data_cell/sparse_term_datacell.cpp
  src/data_cell/sparse_term_datacell.h
  src/index/index_impl.h
  src/quantization/sparse_quantization/sparse_term_computer.h
  tests/test_index.cpp
  tests/test_index.h
  tests/test_sindi.cpp
  tests/test_sparse_index.cpp
Labels: kind/improvement, size/L, module/testing, version/0.17

#1120 docs(ivf): add parameter table for ivf doc
  docs/brute_force.md
  docs/ivf.md
Labels: kind/documentation, size/S, version/0.17

#1116 feat(ivf): support for self-checking and query-based checking of IVF inverted indexes
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/inner_index_interface.cpp
  src/algorithm/inner_index_interface.h
  src/algorithm/ivf.cpp
  src/algorithm/ivf.h
  tests/test_ivf.cpp
  tools/analyze_index/analyze_index.cpp
Labels: kind/improvement, size/L, module/tools, module/testing, version/0.17

#1127 fix: add missing <cstdint> include in commen.h
  src/common.h
Labels: kind/bug, size/XS, version/0.17

#1123 feat(search): extend search request to cover all search cases
  include/vsag/search_request.h
  src/index/index_impl.h
Labels: kind/feature, size/L, version/0.17

#1130 refactor(sindi): remove the dimension check for the sparse vector index
  src/algorithm/sindi/sindi.cpp
  src/index/index_common_param.cpp
  src/utils/util_functions.cpp
Labels: kind/improvement, size/S, module/tools, module/testing, version/0.17, needs-cherry-pick-release-0.16

#1122 feat(sindi): support exclude the footer during deserialize
  src/algorithm/sindi/sindi.cpp
  src/algorithm/sindi/sindi.h
  src/algorithm/sindi/sindi_parameter.cpp
  src/algorithm/sindi/sindi_parameter.h
  src/inner_string_params.h
  tests/test_sindi.cpp
Labels: kind/improvement, size/M, module/testing, version/0.17, needs-cherry-pick-release-0.16

#1118 refactor(headers): improve header include rules
  src/algorithm/brute_force.cpp
  src/algorithm/brute_force.h
  src/algorithm/hgraph.h
  src/algorithm/inner_index_interface.cpp
  src/algorithm/inner_index_interface.h
  src/algorithm/ivf.cpp
  src/algorithm/sindi/sindi.cpp
  src/algorithm/sparse_index.cpp
  src/algorithm/sparse_index.h
  src/impl/bitset/fast_bitset.h
  src/impl/heap/distance_heap.h
  src/impl/kmeans_cluster.h
  src/impl/pruning_strategy.cpp
  src/impl/pruning_strategy.h
  src/impl/pruning_strategy_test.cpp
  src/impl/transform/vector_transformer.h
  src/index/index_common_param.h
  src/index/index_impl.h
  src/index/iterator_filter.h
  src/io/memory_block_io.h
  src/io/memory_io.h
  src/io/mmap_io.cpp
  src/io/mmap_io.h
  src/io/mmap_io_test.cpp
  src/io/reader_io.h
  src/quantization/computer.h
  src/quantization/scalar_quantization/sq4_uniform_quantizer.cpp
  src/quantization/scalar_quantization/sq4_uniform_quantizer.h
  src/simd/avx.cpp
  src/simd/avx2.cpp
  src/simd/avx512.cpp
  src/simd/avx512vpopcntdq.cpp
  src/simd/basic_func_test.cpp
  src/simd/bf16_simd.h
  src/simd/bit_simd.h
  src/simd/fp16_simd.h
  src/simd/fp32_simd.h
  src/simd/generic.cpp
  src/simd/int8_simd.h
  src/simd/neon.cpp
  src/simd/pqfs_simd.h
  src/simd/pqfs_simd_test.cpp
  src/simd/rabitq_simd.cpp
  src/simd/rabitq_simd.h
  src/simd/rabitq_simd_test.cpp
  src/simd/simd_test.cpp
  src/simd/sse.cpp
  src/simd/sve.cpp
  src/storage/footer.h
  src/storage/stream_reader.h
  src/utils/visited_list.h
Labels: kind/improvement, size/XL, module/simd, version/0.17

#1132 feat(SINDI): support set immutable
  src/algorithm/sindi/sindi.cpp
  src/algorithm/sindi/sindi.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
  tests/test_index.h
  tests/test_multi_thread.cpp
  tests/test_sindi.cpp
Labels: kind/improvement, size/L, module/testing, version/0.17

#1144 feat(sindi): add parameter check for sindi
  src/algorithm/sindi/sindi.cpp
  src/algorithm/sindi/sindi_parameter.cpp
  src/algorithm/sindi/sindi_parameter_test.cpp
  src/algorithm/sindi/sindi_test.cpp
  tests/test_sindi.cpp
Labels: kind/improvement, size/L, module/testing, version/0.17

#1139 typo(index): typo error on index's serialize log
  src/algorithm/inner_index_interface.cpp
Labels: kind/improvement, size/XS, version/0.17, needs-cherry-pick-release-0.16

#1117 coverage: improve coverage rate
  include/vsag/vsag_ext.h
  src/algorithm/brute_force.cpp
  src/algorithm/brute_force.h
  src/algorithm/inner_index_interface.h
  src/algorithm/inner_index_interface_test.cpp
  src/impl/bitset/bitset_test.cpp
  src/impl/bitset/fast_bitset_test.cpp
  src/io/async_io.cpp
  src/io/async_io_test.cpp
  src/io/basic_io_test.h
  src/io/buffer_io.cpp
  src/io/buffer_io_test.cpp
  src/io/mmap_io.cpp
  src/io/mmap_io_test.cpp
  src/io/reader_io_test.cpp
  tests/fixtures/fixtures.h
  tests/test_brute_force.cpp
  tests/test_index.cpp
  tests/test_simple_index.cpp
  tests/test_vsag_ext.cpp
Labels: kind/improvement, size/L, module/testing, version/0.17

#1159 fix(index): add check for empty input in index
  src/index/index_impl.h
  src/index/index_impl_test.cpp
Labels: kind/bug, size/L, version/0.17, needs-cherry-pick-release-0.16

#1152 feat(int8): add int8 type support for full-precision quantizer
  src/inner_string_params.h
  src/quantization/CMakeLists.txt
  src/quantization/int8_quantizer.cpp
  src/quantization/int8_quantizer.h
  src/quantization/int8_quantizer_parameter.cpp
  src/quantization/int8_quantizer_parameter.h
  src/quantization/int8_quantizer_parameter_test.cpp
  src/quantization/int8_quantizer_test.cpp
  src/quantization/quantizer_test.h
Labels: kind/improvement, size/XL, module/simd, version/0.17

#1170 refactor(option): modify the minimum block size
  src/options.cpp
Labels: kind/improvement, size/XS, version/0.16

#1167 fix(int8): fix the missing header files issue
  src/factory/CMakeLists.txt
  src/quantization/int8_quantizer.h
Labels: kind/bug, size/XS, version/0.17

#1160 feat(HGraph): support tombstone recovery
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/data_cell/graph_datacell.h
  src/data_cell/graph_interface.h
  src/data_cell/graph_interface_test.cpp
  src/data_cell/sparse_graph_datacell.cpp
  src/data_cell/sparse_graph_datacell.h
  src/impl/label_table.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
  tests/test_index.h
  tools/eval/monitor/recall_monitor.cpp
Labels: kind/improvement, size/L, module/tools, module/testing, version/0.17

#1182 refactor(test): clear ci log and cout test name
  src/impl/searcher/basic_searcher_test.cpp
  tests/test_index.cpp
  tests/test_main.cpp
  tests/test_multi_thread.cpp
Labels: kind/improvement, size/L, module/testing, version/0.17

#1187 tests: speed up functests by reduce dim upperbound
  tests/fixtures/fixtures.cpp
  tests/fixtures/fixtures.h
  tests/test_hgraph.cpp
  tests/test_ivf.cpp
Labels: kind/improvement, size/S, module/testing, version/0.17

#1195 feat(sindi): support passing an allocator into KnnSearch
  src/algorithm/sindi/sindi.cpp
  src/algorithm/sindi/sindi.h
  tests/test_sindi.cpp
Labels: kind/feature, size/M, module/testing, version/0.17

#1193 chore(cmake): clear CMake warnings, add license to the file header
  CMakeLists.txt
  Makefile
  cmake/CheckSIMDCompilerFlag.cmake
  cmake/ColorizeMessage.cmake
  cmake/GenerateVersionHeader.cmake
  examples/cpp/CMakeLists.txt
  extern/cpuinfo/cpuinfo.cmake
  extern/mkl/mkl.cmake
  mockimpl/CMakeLists.txt
  src/CMakeLists.txt
  src/algorithm/CMakeLists.txt
  src/algorithm/ivf_partition/CMakeLists.txt
  src/algorithm/sindi/CMakeLists.txt
  src/attr/CMakeLists.txt
  src/datacell/CMakeLists.txt
  src/factory/CMakeLists.txt
  src/impl/CMakeLists.txt
  src/impl/allocator/CMakeLists.txt
  src/impl/bitset/CMakeLists.txt
  src/impl/cluster/CMakeLists.txt
  src/impl/filter/CMakeLists.txt
  src/impl/heap/CMakeLists.txt
  src/impl/logger/CMakeLists.txt
  src/impl/odescent/CMakeLists.txt
  src/impl/searcher/CMakeLists.txt
  src/impl/thread_pool/CMakeLists.txt
  src/impl/transform/CMakeLists.txt
  src/io/CMakeLists.txt
  src/quantization/CMakeLists.txt
  src/simd/CMakeLists.txt
  src/storage/CMakeLists.txt
  src/utils/CMakeLists.txt
  tests/CMakeLists.txt
  tools/CMakeLists.txt
  tools/analyze_index/CMakeLists.txt
  tools/check_compatibility/CMakeLists.txt
  tools/eval/CMakeLists.txt
  tools/test_performance/CMakeLists.txt
Labels: kind/improvement, size/XL, module/simd, module/tools, module/testing, version/0.17

#1198 fix(cmake): fix wrong message on RUNTIME_AVX512VPOPCNTDQ
  cmake/CheckSIMDCompilerFlag.cmake
Labels: kind/bug, size/M, version/0.17, needs-cherry-pick-release-0.16

#1185 feat(quantization): Introduce QuantizerAdapter to support non-FP32 data types in quantizers
  src/quantization/CMakeLists.txt
  src/quantization/quantizer.h
  src/quantization/quantizer_adapter.cpp
  src/quantization/quantizer_adapter.h
  src/quantization/quantizer_adapter_test.cpp
  src/quantization/quantizer_adapter_test.h
Labels: kind/improvement, size/XL, version/0.17
