Repository antgroup/vsag, pull requests merged in 2025-05, with the labels that each got.

#669 fix compatibility of hnsw
  src/algorithm/hnswlib/hnswalg.cpp
Labels: kind/bug, size/M, version/0.14

#604 support sparse vector in HGraph
  include/vsag/constants.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/hgraph_parameter.cpp
  src/algorithm/hgraph_parameter.h
  src/constants.cpp
  src/data_cell/flatten_datacell.h
  src/data_cell/flatten_datacell_parameter.cpp
  src/data_cell/flatten_interface.h
  src/data_cell/sparse_vector_datacell.inl
  src/data_type.h
  src/impl/basic_searcher.cpp
  src/impl/basic_searcher.h
  src/index/index_common_param.cpp
  src/quantization/sparse_quantization/sparse_quantizer.h
  tests/fixtures/fixtures.cpp
  tests/fixtures/test_dataset.cpp
  tests/fixtures/test_dataset_pool.cpp
  tests/fixtures/test_dataset_pool.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
  tests/test_sparse_index.cpp
  tools/eval/eval_dataset.cpp
  tools/eval/exporter/formatter_lineproto.h
Labels: kind/feature, size/L, module/tools, module/testing, version/0.15

#656 calc random orthogonal matrix lazily
  src/impl/random_orthogonal_matrix.cpp
  src/impl/random_orthogonal_matrix.h
  src/impl/random_orthogonal_matrix_test.cpp
  src/quantization/rabitq_quantization/rabitq_quantizer.h
Labels: kind/improvement, size/M, version/0.15

#662 add pq implement for ivf
  include/vsag/constants.h
  src/algorithm/ivf.cpp
  src/constants.cpp
  tests/test_ivf.cpp
Labels: kind/feature, size/S, module/testing, version/0.15

#674 support concurrent add on bruteforce
  src/algorithm/brute_force.cpp
  src/algorithm/brute_force.h
  src/algorithm/hgraph.cpp
  src/utils/util_functions.cpp
  src/utils/util_functions.h
Labels: kind/improvement, size/L, version/0.15

#676 calc random orthogonal matrix lazily
  src/impl/random_orthogonal_matrix.cpp
  src/impl/random_orthogonal_matrix.h
  src/impl/random_orthogonal_matrix_test.cpp
  src/quantization/rabitq_quantization/rabitq_quantizer.h
Labels: kind/improvement, size/M, version/0.14

#673 fix too much memory used on small dataset
  src/algorithm/hgraph.cpp
Labels: kind/bug, size/XS, version/0.15, needs-cherry-pick-release-0.14

#523 Support basic optimizer
  include/vsag/constants.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/hgraph_parameter.cpp
  src/algorithm/hgraph_parameter.h
  src/algorithm/ivf.cpp
  src/constants.cpp
  src/data_cell/flatten_datacell.h
  src/data_cell/flatten_interface.h
  src/impl/basic_optimizer.cpp
  src/impl/basic_optimizer.h
  src/impl/basic_searcher.cpp
  src/impl/basic_searcher.h
  src/impl/basic_searcher_test.cpp
  src/impl/runtime_parameter.h
  src/inner_string_params.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/feature, size/XL, module/tools, module/testing, version/0.15

#678 fix compatibility of hnsw
  src/algorithm/hnswlib/hnswalg.cpp
Labels: kind/bug, size/M, version/0.13

#679 compile openblas dynamic arch
  extern/openblas/openblas.cmake
Labels: kind/improvement, size/S, version/0.14

#649 fix hnsw core dump when destructing
  include/vsag/errors.h
  src/index/hnsw.cpp
  src/index/hnsw.h
  tests/test_hnsw_new.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/bug, size/L, module/testing, needs-cherry-pick-release-0.13, version/0.15, needs-cherry-pick-release-0.14

#677 speed up build
  .circleci/config.yml
  .circleci/fresh_ci_cache.commit
  .github/workflows/asan_build_and_test.yml
  .github/workflows/asan_with_simd_option.yml
  .github/workflows/check_compatibility.yml
  .github/workflows/coverage.yml
  .github/workflows/lint.yml
  .github/workflows/tsan_build_and_test.yml
  CMakeLists.txt
  Makefile
  tests/test_hgraph.cpp
  tests/test_ivf.cpp
Labels: kind/improvement, size/M, module/testing, version/0.15

#665 fix curl related compile issue in cpr
  extern/cpr/cpr.cmake
  extern/cpr/fix_curl.patch
Labels: kind/bug, size/M, version/0.15

#641 use VsagException instead std errors
  src/algorithm/brute_force.cpp
  src/algorithm/hgraph.cpp
  src/algorithm/inner_index_interface.h
  src/algorithm/ivf.cpp
  src/data_cell/bucket_datacell.h
  src/data_cell/extra_info_interface.cpp
  src/impl/conjugate_graph.cpp
  src/impl/odescent_graph_builder.cpp
  src/impl/pruning_strategy.cpp
  src/index/hnsw.cpp
  src/index/index_common_param.cpp
  src/index_feature_list.cpp
  src/io/async_io.h
  src/io/buffer_io.h
  src/quantization/fp32_quantizer.h
  src/quantization/quantizer_parameter.cpp
  src/quantization/rabitq_quantization/rabitq_quantizer.h
  src/quantization/scalar_quantization/bf16_quantizer.h
  src/quantization/scalar_quantization/sq4_quantizer.h
  src/quantization/scalar_quantization/sq4_uniform_quantizer.h
  src/quantization/scalar_quantization/sq8_quantizer.h
  src/quantization/scalar_quantization/sq8_uniform_quantizer.h
  src/stream_reader.cpp
  src/utils/util_functions.cpp
Labels: kind/improvement, size/L, version/0.15

#692 add batch4 simd for fp32 compute
  src/simd/avx.cpp
  src/simd/avx2.cpp
  src/simd/avx512.cpp
  src/simd/fp32_simd.cpp
  src/simd/fp32_simd.h
  src/simd/fp32_simd_test.cpp
  src/simd/generic.cpp
  src/simd/sse.cpp
Labels: kind/improvement, size/XL, module/simd, version/0.15

#680 use DistanceHeap replace MaxHeap
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/ivf.cpp
  src/algorithm/ivf.h
  src/algorithm/pyramid.cpp
  src/algorithm/pyramid.h
  src/algorithm/sparse_index.cpp
  src/algorithm/sparse_index.h
  src/impl/basic_searcher.cpp
  src/impl/basic_searcher.h
  src/impl/basic_searcher_test.cpp
  src/impl/pruning_strategy.cpp
  src/impl/pruning_strategy.h
Labels: kind/improvement, size/L, version/0.15

#700 add default value for optimizer
  src/algorithm/hgraph.cpp
  src/data_cell/flatten_datacell.h
  src/impl/basic_optimizer.cpp
Labels: kind/improvement, size/S, version/0.15

#668 enables the upper bound of ef_search, max_degree and ef_construction
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph_parameter.cpp
  src/algorithm/hnswlib/hnswalg.h
  src/common.h
  src/index/hnsw.cpp
  src/index/hnsw_zparameters.cpp
  src/index/hnsw_zparameters_test.cpp
Labels: kind/improvement, size/L, module/tools

#682 resolve initialization order issue for static variables
  src/algorithm/brute_force.cpp
  src/algorithm/hgraph.cpp
  src/algorithm/ivf.cpp
  src/impl/basic_searcher_test.cpp
Labels: kind/bug, size/L, version/0.15

#704 [skip ci]update output path in perf yaml
  .github/perf-90.yml
  .github/perf-95.yml
  .github/perf-99.yml
  .github/perf-mini.yml
Labels: size/XS, version/0.15

#697 Implement of batch4 simd compute on HGraph
  src/data_cell/bucket_datacell.h
  src/data_cell/flatten_datacell.h
  src/quantization/computer.h
  src/quantization/fp32_quantizer.h
  src/quantization/product_quantization/pq_fastscan_quantizer.h
  src/quantization/product_quantization/pq_fastscan_quantizer_test.cpp
  src/quantization/product_quantization/product_quantizer.h
  src/quantization/quantizer.h
  src/quantization/quantizer_test.h
  src/quantization/rabitq_quantization/rabitq_quantizer.h
  src/quantization/scalar_quantization/bf16_quantizer.h
  src/quantization/scalar_quantization/fp16_quantizer.h
  src/quantization/scalar_quantization/sq4_quantizer.h
  src/quantization/scalar_quantization/sq4_uniform_quantizer.h
  src/quantization/scalar_quantization/sq8_quantizer.h
  src/quantization/scalar_quantization/sq8_uniform_quantizer.h
  src/quantization/sparse_quantization/sparse_quantizer.h
  src/utils/function_exists_check.h
Labels: kind/improvement, size/L, version/0.15

#705 init the cpuinfo before other simd functions
  src/simd/CMakeLists.txt
  src/simd/simd_status.cpp
  src/simd/simd_status.h
Labels: kind/bug, kind/improvement, size/M, module/simd, version/0.15

#694 support merge on ivf index
  src/algorithm/ivf.cpp
  src/algorithm/ivf.h
  src/data_cell/bucket_datacell.h
  src/data_cell/bucket_interface.h
  src/data_cell/flatten_datacell.h
  src/data_cell/flatten_interface.h
  src/index/index_impl.h
  src/label_table.cpp
  src/label_table.h
  src/utils/util_functions.cpp
  src/utils/util_functions.h
  tests/test_index.cpp
  tests/test_index.h
  tests/test_ivf.cpp
Labels: kind/feature, size/L, module/testing, version/0.15

#698 disable simd instructions in diskann
  extern/diskann/DiskANN/include/simd_utils.h
  extern/diskann/DiskANN/src/distance.cpp
  extern/diskann/DiskANN/src/index.cpp
  extern/diskann/DiskANN/src/pq.cpp
  extern/diskann/DiskANN/src/pq_flash_index.cpp
  extern/diskann/diskann.cmake
Labels: kind/bug, size/M, needs-cherry-pick-release-0.13, version/0.15, needs-cherry-pick-release-0.14

#630 support building graph by Odescent in HGraph
  .github/perf-90.yml
  examples/cpp/312_feature_odescent.cpp
  include/vsag/constants.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/hgraph_parameter.cpp
  src/algorithm/hgraph_parameter.h
  src/constants.cpp
  src/inner_string_params.h
  tests/test_hgraph.cpp
Labels: kind/feature, size/L, module/tools, module/testing, version/0.15

#708 reduce alloc buffer on merge
  src/algorithm/ivf.cpp
  src/data_cell/flatten_datacell.h
  src/utils/util_functions.cpp
Labels: kind/improvement, size/S, version/0.15

#702 support ivfpq fastscan
  src/algorithm/ivf.cpp
  src/algorithm/ivf.h
  src/data_cell/bucket_datacell.h
  src/data_cell/bucket_interface.cpp
  src/data_cell/bucket_interface.h
  src/quantization/product_quantization/pq_fastscan_quantizer.h
  src/quantization/product_quantization/pq_fastscan_quantizer_test.cpp
  src/quantization/product_quantization/product_quantizer_test.cpp
  src/quantization/quantizer.h
  src/quantization/quantizer_parameter.cpp
  src/quantization/scalar_quantization/sq4_quantizer_test.cpp
  tests/test_index.cpp
  tests/test_ivf.cpp
Labels: kind/feature, size/L, module/testing, version/0.15

#707 use thread_pool to speedup kmeans
  src/impl/kmeans_cluster.cpp
  src/impl/kmeans_cluster.h
  src/safe_thread_pool.h
Labels: kind/improvement, size/M, version/0.15

#726 update perf-90
  .github/perf-90.yml
  src/data_cell/extra_info_datacell_test.cpp
Labels: kind/improvement, size/S, version/0.15

#703 speedup compile on CI test
  .circleci/fresh_ci_cache.commit
  .github/workflows/asan_build_and_test.yml
  .github/workflows/coverage.yml
  .github/workflows/tsan_build_and_test.yml
  scripts/change_mtime.sh
Labels: kind/improvement, size/M, version/0.16

#717 kmeans train for huge K and data count
  src/impl/kmeans_cluster.cpp
  src/impl/kmeans_cluster.h
  src/quantization/product_quantization/product_quantizer_test.cpp
  src/quantization/quantizer_test.h
Labels: kind/bug, size/L, version/0.15

#724 fix double assignment for max_degree in HNSW Merge
  src/index/hnsw.cpp
  tests/test_hnsw_new.cpp
Labels: kind/bug, size/S, module/testing

#720 resolve not properly handling invalid IDs in CalDistanceById
  src/algorithm/hgraph.cpp
  tests/test_index.cpp
Labels: kind/bug, size/S, module/testing, needs-cherry-pick-release-0.14

#736 remove mtime change on ci test
  .circleci/fresh_ci_cache.commit
  .github/workflows/asan_build_and_test.yml
  .github/workflows/coverage.yml
  .github/workflows/tsan_build_and_test.yml
Labels: kind/improvement, size/S, version/0.15

#733 add simd operator to cal residual
  src/simd/avx.cpp
  src/simd/avx2.cpp
  src/simd/avx512.cpp
  src/simd/fp32_simd.cpp
  src/simd/fp32_simd.h
  src/simd/fp32_simd_test.cpp
  src/simd/generic.cpp
  src/simd/sse.cpp
Labels: kind/improvement, size/L, module/simd, version/0.15

#721 add computable operators for bitset
  include/vsag/bitset.h
  src/bitset_impl.cpp
  src/bitset_impl.h
  src/bitset_impl_test.cpp
Labels: kind/feature, size/L

#729 add new interface for attr search
  include/vsag/attribute.h
  include/vsag/constants.h
  include/vsag/dataset.h
  include/vsag/index.h
  include/vsag/search_request.h
  src/constants.cpp
  src/dataset_impl.h
Labels: kind/feature, size/L, version/0.15

#737 add fast index create for inner index
  src/algorithm/brute_force.cpp
  src/algorithm/inner_index_interface.cpp
  src/algorithm/inner_index_interface.h
  src/algorithm/inner_index_interface_test.cpp
  src/utils/util_functions.cpp
  src/utils/util_functions.h
Labels: kind/improvement, size/L, version/0.15

#719 resolving core dumps caused by incorrect resizing in sparse datacell
  src/data_cell/sparse_vector_datacell.h
Labels: kind/bug, size/XS

#728 make the member access of Resource private
  include/vsag/resource.h
  src/index/index_common_param.cpp
Labels: kind/improvement, size/XS, version/0.15

#742 fix non-memory io's incorrect result on large dataset
  src/data_cell/flatten_datacell.h
Labels: kind/bug, size/XS, version/0.15, needs-cherry-pick-release-0.14

#745 add merge support for ivfpqfs
  src/algorithm/ivf.cpp
  src/data_cell/bucket_datacell.h
  src/data_cell/bucket_interface.h
  src/quantization/product_quantization/pq_fastscan_quantizer.h
  src/quantization/product_quantization/pq_fastscan_quantizer_test.cpp
  src/quantization/quantizer.h
Labels: kind/feature, size/L, version/0.15

#750 speedup kmeans by use hgraph for large k
  src/impl/kmeans_cluster.cpp
  src/impl/kmeans_cluster.h
Labels: kind/improvement, size/M, version/0.15

#730 fix several bugs for performance
  src/algorithm/hgraph.cpp
  src/quantization/scalar_quantization/scalar_quantization_trainer.cpp
  src/quantization/scalar_quantization/scalar_quantization_trainer.h
  src/quantization/scalar_quantization/sq8_uniform_quantizer.h
Labels: size/S

#771 reduce test log level to avoid too much debug logs
  tests/test_main.cpp
Labels: kind/improvement, size/XS, module/testing, version/0.15

#764 speed up fast_bitset by use simd operators
  mockimpl/CMakeLists.txt
  src/impl/bitset/fast_bitset.cpp
Labels: kind/improvement, size/M, version/0.15

#769 compile openblas dynamic arch
  extern/openblas/openblas.cmake
Labels: kind/improvement, size/S, version/0.15
