Repository antgroup/vsag, pull requests merged in 2025-01, with the labels that each got.

#288 replace the implementation of thread pool in diskann
  src/default_thread_pool.h
  src/factory/factory.cpp
  src/index/diskann.cpp
  src/index/diskann.h
  src/safe_thread_pool.h
Labels: kind/improvement, size/M

#284 add index_feature for hnsw
  src/index/hnsw.cpp
  src/index/hnsw.h
Labels: kind/feature, size/M

#270 update makefile and remove outdated benchs directory
  DEVELOPMENT.md
  Makefile
  benchs/README.md
  benchs/benchmark/__init__.py
  benchs/benchmark/bench_index.py
  benchs/benchmark/dataset.py
  benchs/run.py
  benchs/run.yaml
  scripts/format-cpp.sh
Labels: kind/improvement, size/L

#286 [skip ci]introduce clang-tidy as cpp linter
  .clang-tidy
  .github/workflows/lint.yml
  Makefile
  scripts/linters/run-clang-tidy.py
  src/algorithm/hgraph.cpp
  src/algorithm/hnswlib/.clang-tidy
  src/index/diskann.h
  src/index/hgraph_zparameters.cpp
  src/index/hnsw.cpp
  src/simd/.clang-tidy
  src/vsag.cpp
Labels: kind/improvement, size/XL

#293 [skip ci]add contributors bagde in README
  README.md
Labels: kind/documentation, size/XS

#295 rename index_feature to index_features
  include/vsag/index.h
  include/vsag/index_features.h
  src/algorithm/hgraph.h
  src/index_feature_list.h
Labels: kind/improvement, size/XS

#281 optimize hgraph
  src/algorithm/hgraph.cpp
  src/index/hgraph_index.h
  src/simd/avx512.cpp
Labels: kind/improvement, size/S

#291 use normalize for sq4 uniform cosine compute
  src/quantization/sq4_uniform_quantizer.h
  src/quantization/sq4_uniform_quantizer_test.cpp
  src/quantization/sq8_uniform_quantizer.h
Labels: kind/improvement, size/M

#245 replace logger inside diskann with vsag logger, and improve tests output
  extern/diskann/DiskANN/include/logger_impl.h
  extern/diskann/DiskANN/src/logger.cpp
  extern/diskann/diskann.cmake
  src/bitset_impl_test.cpp
  src/index/diskann_test.cpp
  src/vsag.cpp
  tests/CMakeLists.txt
  tests/fixtures/test_logger.cpp
  tests/fixtures/test_logger.h
  tests/test_main.cpp
  tests/test_multi_thread.cpp
Labels: kind/improvement, size/L, version/0.13, module/testing

#301 enable examples in the compilation by default
  CMakeLists.txt
  examples/cpp/custom_memory_allocator.cpp
Labels: kind/improvement, size/XS

#303 remove unuseful log for ut and ft
  CMakeLists.txt
  src/index/diskann.cpp
  src/index/hnsw.cpp
  tests/test_random_allocator.cpp
Labels: size/S

#231 implement the interfaces for add, knnsearch, serialize in pyramid
  examples/cpp/CMakeLists.txt
  examples/cpp/simple_pyramid.cpp
  include/vsag/constants.h
  src/constants.cpp
  src/engine.cpp
  src/index/pyramid.cpp
  src/index/pyramid.h
  src/index/pyramid_zparameters.cpp
  src/index/pyramid_zparameters.h
  src/safe_allocator.h
  tests/fixtures/test_dataset.cpp
  tests/fixtures/test_dataset.h
  tests/fixtures/test_dataset_pool.cpp
  tests/fixtures/test_dataset_pool.h
  tests/test_index.cpp
  tests/test_pyramid.cpp
Labels: kind/feature, size/XL, version/0.13

#304 update codecov configuration
  .codecov.yml
  .github/workflows/lcov.yml
  .gitignore
  CMakeLists.txt
  scripts/collect_cpp_coverage.sh
  src/CMakeLists.txt
Labels: kind/improvement, size/M

#292 list new examples for cpp & python
  examples/cpp/todo_examples/101_index_hnsw.cpp
  examples/cpp/todo_examples/102_index_diskann.cpp
  examples/cpp/todo_examples/103_index_hgraph.cpp
  examples/cpp/todo_examples/104_index_fresh_hnsw.cpp
  examples/cpp/todo_examples/105_index_brute_force.cpp
  examples/cpp/todo_examples/201_custom_allocator.cpp
  examples/cpp/todo_examples/202_custom_logger.cpp
  examples/cpp/todo_examples/203_custom_thread_pool.cpp
  examples/cpp/todo_examples/301_feature_filter.cpp
  examples/cpp/todo_examples/302_feature_range_search.cpp
  examples/cpp/todo_examples/303_feature_update.cpp
  examples/cpp/todo_examples/304_feature_enhance_graph.cpp
  examples/cpp/todo_examples/305_feature_remove.cpp
  examples/cpp/todo_examples/306_feature_calculate_distance_by_id.cpp
  examples/cpp/todo_examples/307_feature_check_features.cpp
  examples/cpp/todo_examples/308_feature_estimate_memory.cpp
  examples/cpp/todo_examples/401-persistent.cpp
  examples/python/todo_examples/101_index_hnsw.py
  examples/python/todo_examples/102_index_diskann.py
  examples/python/todo_examples/103_index_hgraph.py
  examples/python/todo_examples/104_index_fresh_hnsw.py
  examples/python/todo_examples/105_index_brute_force.py
  examples/python/todo_examples/201_custom_allocator.py
  examples/python/todo_examples/202_custom_logger.py
  examples/python/todo_examples/203_custom_thread_pool.py
  examples/python/todo_examples/301_feature_filter.py
  examples/python/todo_examples/302_feature_range_search.py
  examples/python/todo_examples/303_feature_update.py
  examples/python/todo_examples/304_feature_enhance_graph.py
  examples/python/todo_examples/305_feature_remove.py
  examples/python/todo_examples/306_feature_calculate_distance_by_id.py
  examples/python/todo_examples/307_feature_check_features.py
  examples/python/todo_examples/308_feature_estimate_memory.py
  examples/python/todo_examples/401-persistent.py
Labels: kind/feature, size/L

#104 add check for number of elements in diskann
  src/index/diskann.cpp
  src/index/diskann_test.cpp
Labels: kind/improvement, size/M

#294 introduce third party yaml-cpp for tools
  extern/yaml-cpp/yaml-cpp.cmake
Labels: kind/improvement, size/S

#311 upgrade the lcov version in github ci
  .github/codecov.yml
  .github/workflows/lcov.yml
  scripts/collect_cpp_coverage.sh
Labels: kind/improvement, size/M

#307 add github action to update the ci image automaticlly
  .github/workflows/update-ci-image.yml
Labels: kind/improvement, size/S

#305 add distances for test_performance
  tools/eval_dataset.cpp
  tools/eval_dataset.h
Labels: kind/improvement, size/S

#316 update coverage configuration
  .github/codecov.yml
  .github/workflows/coverage.yml
  scripts/collect_cpp_coverage.sh
Labels: kind/improvement, size/M

#327 add test to increase coverage rate
  scripts/collect_cpp_coverage.sh
  tests/test_hgraph.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/improvement, size/L

#299 introduce brute_force index
  include/vsag/constants.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/constants.cpp
  src/engine.cpp
  src/index/brute_force.cpp
  src/index/brute_force.h
  src/index/brute_force_parameter.cpp
  src/index/brute_force_parameter.h
  src/label_table.h
  src/typing.h
  tests/test_brute_force.cpp
Labels: kind/feature, size/XXL

#289 add estimate feature & test
  include/vsag/index_features.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/index/hgraph_index.cpp
  src/index/hgraph_index.h
  src/index/index_common_param.cpp
  src/resource.cpp
  tests/fixtures/fixtures.cpp
  tests/fixtures/memory_record_allocator.h
  tests/fixtures/random_allocator.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/feature, size/L

#332 optimize the implementation logic of TestSerializeReaderSet
  tests/fixtures/test_reader.h
  tests/test_index.cpp
Labels: kind/improvement, version/0.13

#308 support safe update
  include/vsag/index.h
  src/index/hnsw.cpp
  src/index/hnsw.h
  tests/test_index.cpp
Labels: kind/improvement, size/M, version/0.13

#328 increase the code coverage of hnswlib
  src/algorithm/hnswlib/algorithm_interface.h
  src/algorithm/hnswlib/block_manager.cpp
  src/algorithm/hnswlib/block_manager.h
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
  src/algorithm/hnswlib/hnswalg_static.h
  src/algorithm/hnswlib/hnswlib.h
  src/default_thread_pool.cpp
  src/index/pyramid.cpp
  src/index/pyramid.h
  src/safe_thread_pool_test.cpp
  tests/test_hnsw_new.cpp
  tests/test_index_old.cpp
Labels: kind/improvement, size/XL, version/0.13

#331 add example for brute force and hgraph
  examples/cpp/CMakeLists.txt
  examples/cpp/todo_examples/103_index_hgraph.cpp
  examples/cpp/todo_examples/105_index_brute_force.cpp
  examples/cpp/todo_examples/CMakeLists.txt
Labels: kind/feature, size/L, version/0.13

#330 improve coverage rate
  src/io/memory_block_io_parameter_test.cpp
  src/io/memory_io_parameter_test.cpp
  src/parameter_test.h
  src/quantization/fp32_quantizer_parameter_test.cpp
  src/quantization/scalar_quantization/sq4_quantizer_parameter_test.cpp
  src/quantization/scalar_quantization/sq4_uniform_quantizer.h
  src/quantization/scalar_quantization/sq4_uniform_quantizer_parameter_test.cpp
  src/quantization/scalar_quantization/sq8_quantizer_parameter_test.cpp
  src/quantization/scalar_quantization/sq8_uniform_quantizer.h
  src/quantization/scalar_quantization/sq8_uniform_quantizer_parameter_test.cpp
  src/utils.cpp
  src/utils.h
  tests/test_brute_force.cpp
  tests/test_hgraph.cpp
Labels: kind/improvement, size/L, version/0.13

#335 fix asan multi thread
  src/algorithm/hnswlib/algorithm_interface.h
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
  src/algorithm/hnswlib/hnswalg_static.h
  src/index/hnsw.cpp
  src/index/hnsw_test.cpp
  tests/test_index_old.cpp
  tests/test_multi_thread.cpp
Labels: kind/bug, size/L

#334 add prefetch implement
  src/data_cell/flatten_datacell.h
  src/io/memory_block_io.h
  src/io/memory_io.h
  src/prefetch.cpp
  src/prefetch.h
  src/simd/basic_func.cpp
  src/simd/basic_func.h
  src/simd/generic.cpp
  src/simd/sse.cpp
Labels: kind/improvement, size/L

#234 introduce new eval tool: eval_performance
  tools/CMakeLists.txt
  tools/eval/CMakeLists.txt
  tools/eval/build_eval_case.cpp
  tools/eval/build_eval_case.h
  tools/eval/eval_case.cpp
  tools/eval/eval_case.h
  tools/eval/eval_config.cpp
  tools/eval/eval_config.h
  tools/eval/eval_dataset.cpp
  tools/eval/eval_dataset.h
  tools/eval/monitor/duration_monitor.cpp
  tools/eval/monitor/duration_monitor.h
  tools/eval/monitor/latency_monitor.cpp
  tools/eval/monitor/latency_monitor.h
  tools/eval/monitor/memory_peak_monitor.cpp
  tools/eval/monitor/memory_peak_monitor.h
  tools/eval/monitor/monitor.cpp
  tools/eval/monitor/monitor.h
  tools/eval/monitor/recall_monitor.cpp
  tools/eval/monitor/recall_monitor.h
  tools/eval/search_eval_case.cpp
  tools/eval/search_eval_case.h
  tools/eval_performance.cpp
  tools/test_performance.cpp
Labels: kind/improvement, size/XXL, module/tools, version/0.13

#287 implement optimized nndescent in diskann
  include/vsag/constants.h
  src/allocator_wrapper.h
  src/constants.cpp
  src/impl/odescent_graph_builder.cpp
  src/impl/odescent_graph_builder.h
  src/impl/odescent_graph_builder_test.cpp
  src/index/diskann.cpp
  src/index/diskann.h
  src/index/diskann_zparameters.cpp
  src/index/diskann_zparameters.h
  tests/test_brute_force.cpp
  tests/test_diskann.cpp
  tests/test_hgraph.cpp
  tools/test_performance.cpp
Labels: kind/feature, size/XL, version/0.13

#317 support update in conjugate graph
  src/impl/conjugate_graph.cpp
  src/impl/conjugate_graph.h
  src/impl/conjugate_graph_test.cpp
  src/index/hnsw.cpp
  tests/test_index.cpp
  tests/test_index_old.cpp
  tests/test_multi_thread.cpp
Labels: kind/improvement, size/L, version/0.13

#333 add examples for hnsw, diskann, enhance graph and range search
  examples/cpp/todo_examples/101_index_hnsw.cpp
  examples/cpp/todo_examples/102_index_diskann.cpp
  examples/cpp/todo_examples/104_index_fresh_hnsw.cpp
  examples/cpp/todo_examples/302_feature_range_search.cpp
  examples/cpp/todo_examples/304_feature_enhance_graph.cpp
  examples/cpp/todo_examples/CMakeLists.txt
  src/engine.cpp
  src/index/hnsw_zparameters.cpp
  src/parameter_generator.cpp
  tests/test_index_old.cpp
Labels: kind/feature, size/XL, version/0.13

#340 introduce filter & remove example
  examples/cpp/todo_examples/301_feature_filter.cpp
  examples/cpp/todo_examples/305_feature_remove.cpp
  examples/cpp/todo_examples/CMakeLists.txt
Labels: kind/feature, size/L, version/0.13

#346 use ubuntu-22.04 to check clang-format
  .github/workflows/asan_build_and_test.yml
Labels: kind/improvement, size/XS

#329 [skip ci]add arXiv and codecov badge
  README.md
Labels: kind/documentation, kind/improvement, size/XS, version/0.13

#343 add yaml config for eval_performance
  .circleci/fresh_ci_cache.commit
  CMakeLists.txt
  docs/eval_performance.md
  tools/CMakeLists.txt
  tools/eval/CMakeLists.txt
  tools/eval/build_eval_case.cpp
  tools/eval/eval_config.cpp
  tools/eval/eval_config.h
  tools/eval/search_eval_case.cpp
  tools/eval_performance.cpp
  tools/eval_template.yaml
Labels: kind/improvement, size/L

#341 add example customize
  examples/cpp/CMakeLists.txt
  examples/cpp/custom_logger.cpp
  examples/cpp/custom_memory_allocator.cpp
  examples/cpp/todo_examples/201_custom_allocator.cpp
  examples/cpp/todo_examples/202_custom_logger.cpp
  examples/cpp/todo_examples/203_custom_thread_pool.cpp
  examples/cpp/todo_examples/CMakeLists.txt
Labels: size/XL, version/0.13

#348 update coverage config
  .github/codecov.yml
  src/simd/CMakeLists.txt
Labels: kind/improvement, size/XS, version/0.13

#123 introduce simple resource_pool
  src/CMakeLists.txt
  src/utils/resource_object.h
  src/utils/resource_object_pool.h
  src/utils/visited_list.h
  src/utils/visited_list_test.cpp
Labels: kind/improvement, size/L, version/0.13

#349 fix max_degree error
  src/data_cell/graph_datacell_parameter.cpp
Labels: kind/bug, size/XS

#353 use CHECK instead of REQUIRE for some index tests
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/improvement, size/S, version/0.13

#315 enable bugprone-* options in clang-tidy
  .clang-tidy
  src/algorithm/hgraph.cpp
  src/distances.cpp
  src/factory/factory.cpp
  src/impl/conjugate_graph.cpp
  src/impl/odescent_graph_builder.cpp
  src/index/brute_force.cpp
  src/index/diskann.cpp
  src/index/hnsw.cpp
  src/index/pyramid.cpp
  src/options.cpp
  src/parameter_generator.cpp
  src/stream_reader.cpp
  src/utils.cpp
Labels: kind/improvement, size/L, version/0.13

#352 fix occasionally ft fail while use conjugate graph
  tests/test_index_old.cpp
Labels: kind/bug, size/S, version/0.13

#344 support allocator in conjugate graph
  src/impl/conjugate_graph.cpp
  src/impl/conjugate_graph.h
  src/impl/conjugate_graph_test.cpp
  src/index/hnsw.cpp
  src/index/hnsw.h
Labels: kind/improvement, size/M, version/0.13

#345 support build sparse graph in ODescent
  src/impl/odescent_graph_builder.cpp
  src/impl/odescent_graph_builder.h
  src/impl/odescent_graph_builder_test.cpp
Labels: kind/improvement, size/L

#363 modify component codecov threshold
  .github/codecov.yml
Labels: kind/improvement, size/XS, version/0.13

#339 add index persistent example
  examples/cpp/todo_examples/401-persistent.cpp
  examples/cpp/todo_examples/401_persistent_kv.cpp
  examples/cpp/todo_examples/402_persistent_streaming.cpp
  examples/cpp/todo_examples/CMakeLists.txt
Labels: kind/improvement, size/L, version/0.13

#358 format ut and ft
  src/bitset_impl_test.cpp
  src/data_cell/flatten_datacell_test.cpp
  src/data_cell/graph_datacell_test.cpp
  src/data_cell/sparse_graph_datacell_test.cpp
  src/dataset_impl_test.cpp
  src/default_allocator_test.cpp
  src/default_logger_test.cpp
  src/factory/factory_test.cpp
  src/footer_test.cpp
  src/impl/conjugate_graph_test.cpp
  src/impl/odescent_graph_builder_test.cpp
  src/index/diskann_test.cpp
  src/index/hgraph_zparameters_test.cpp
  src/index/index_commom_param_test.cpp
  src/index_feature_list_test.cpp
  src/io/io_read_object.h
  src/io/memory_block_io_parameter_test.cpp
  src/io/memory_block_io_test.cpp
  src/io/memory_io_parameter_test.cpp
  src/io/memory_io_test.cpp
  src/logger_test.cpp
  src/options_test.cpp
  src/prefetch_test.cpp
  src/quantization/fp32_quantizer_parameter_test.cpp
  src/quantization/fp32_quantizer_test.cpp
  src/quantization/scalar_quantization/sq4_quantizer_parameter_test.cpp
  src/quantization/scalar_quantization/sq4_quantizer_test.cpp
  src/quantization/scalar_quantization/sq4_uniform_quantizer_parameter_test.cpp
  src/quantization/scalar_quantization/sq4_uniform_quantizer_test.cpp
  src/quantization/scalar_quantization/sq8_quantizer_parameter_test.cpp
  src/quantization/scalar_quantization/sq8_quantizer_test.cpp
  src/quantization/scalar_quantization/sq8_uniform_quantizer_parameter_test.cpp
  src/quantization/scalar_quantization/sq8_uniform_quantizer_test.cpp
  src/safe_allocator_test.cpp
  src/safe_thread_pool_test.cpp
  src/simd/basic_func_test.cpp
  src/simd/fp32_simd_test.cpp
  src/simd/normalize_test.cpp
  src/simd/simd_test.cpp
  src/simd/sq4_simd_test.cpp
  src/simd/sq4_uniform_simd_test.cpp
  src/simd/sq8_simd_test.cpp
  src/simd/sq8_uniform_simd_test.cpp
  src/utils/visited_list_test.cpp
  tests/test_bitset.cpp
  tests/test_cpuinfo.cpp
  tests/test_engine.cpp
  tests/test_factory.cpp
  tests/test_json.cpp
  tests/test_multi_thread.cpp
  tests/test_options.cpp
  tests/test_pyramid.cpp
  tests/test_random_allocator.cpp
  tests/test_random_index.cpp
  tests/test_simple_index.cpp
  tests/test_utils.cpp
  tests/test_vsag_ext.cpp
Labels: kind/improvement, size/L, version/0.13, version/0.14

#361 fix the issue caused by passing in invalid vectors
  extern/diskann/DiskANN/src/pq.cpp
  tests/fixtures/test_dataset.cpp
  tests/fixtures/test_dataset.h
  tests/fixtures/test_dataset_pool.cpp
  tests/fixtures/test_dataset_pool.h
  tests/test_diskann.cpp
  tests/test_hgraph.cpp
  tests/test_hnsw_new.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/bug, size/L, version/0.13

#364 add update example and remove all outdated examples
  examples/cpp/101_index_hnsw.cpp
  examples/cpp/102_index_diskann.cpp
  examples/cpp/103_index_hgraph.cpp
  examples/cpp/104_index_fresh_hnsw.cpp
  examples/cpp/105_index_brute_force.cpp
  examples/cpp/201_custom_allocator.cpp
  examples/cpp/202_custom_logger.cpp
  examples/cpp/203_custom_thread_pool.cpp
  examples/cpp/301_feature_filter.cpp
  examples/cpp/302_feature_range_search.cpp
  examples/cpp/303_feature_remove.cpp
  examples/cpp/304_feature_enhance_graph.cpp
  examples/cpp/305_feature_update.cpp
  examples/cpp/306_feature_calculate_distance_by_id.cpp
  examples/cpp/307_feature_check_features.cpp
  examples/cpp/308_feature_estimate_memory.cpp
  examples/cpp/401_persistent_kv.cpp
  examples/cpp/402_persistent_streaming.cpp
  examples/cpp/CMakeLists.txt
  examples/cpp/example_conjugate_graph.cpp
  examples/cpp/example_diskann.cpp
  examples/cpp/example_engine.cpp
  examples/cpp/example_fresh_hnsw.cpp
  examples/cpp/example_hnsw.cpp
  examples/cpp/simple_hgraph_sq8.cpp
  examples/cpp/simple_hnsw.cpp
  examples/cpp/simple_pyramid.cpp
  examples/cpp/todo_examples/308_feature_estimate_memory.cpp
  examples/cpp/todo_examples/CMakeLists.txt
  examples/cpp/vsag_ext_example.cpp
  mockimpl/CMakeLists.txt
Labels: kind/improvement, size/XXL, version/0.13

#310 implement the interfaces for range search, filter in pyramid
  src/index/pyramid.cpp
  src/index/pyramid.h
  tests/fixtures/test_dataset.cpp
  tests/test_index.cpp
  tests/test_pyramid.cpp
Labels: kind/feature, size/L, version/0.14

#351 support basic searcher
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
  src/data_cell/flatten_datacell.h
  src/data_cell/flatten_interface.h
  src/impl/basic_searcher.cpp
  src/impl/basic_searcher.h
  src/impl/basic_searcher_test.cpp
Labels: kind/feature, size/L, version/0.13

#365 set threshold coverage from (1%)% to 1%
  .github/codecov.yml
Labels: kind/improvement, size/XS, version/0.13

#337 Add a batch interface for getDistanceByLabel
  include/vsag/index.h
  src/algorithm/hnswlib/algorithm_interface.h
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
  src/algorithm/hnswlib/hnswalg_static.h
  src/index/hnsw.h
  tests/test_hnsw_new.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: size/L, version/0.14
