Repository antgroup/vsag, pull requests merged in 2025-08, with the labels that each got.

#994 improve ivf parallel search
  src/algorithm/ivf.cpp
  src/impl/basic_searcher.h
Labels: kind/improvement, size/M, version/0.16

#969 make thirdparty library static
  extern/cpuinfo/cpuinfo.cmake
  src/simd/CMakeLists.txt
Labels: kind/improvement, size/XS, module/simd, version/0.16

#1002 refactor serialize test
  src/algorithm/ivf_partition/gno_imi_partition_test.cpp
  src/algorithm/ivf_partition/ivf_nearest_partition_test.cpp
  src/algorithm/sindi/sindi_test.cpp
  src/attr/attr_type_schema.cpp
  src/attr/attr_value_map_test.cpp
  src/attr/multi_bitset_manager_test.cpp
  src/data_cell/attribute_bucket_inverted_datacell_test.cpp
  src/data_cell/bucket_datacell_test.cpp
  src/data_cell/extra_info_interface_test.cpp
  src/data_cell/flatten_interface_test.cpp
  src/data_cell/graph_interface_test.cpp
  src/data_cell/sparse_vector_datacell_test.cpp
  src/impl/bitset/sparse_bitset_test.cpp
  src/impl/transform/fht_kac_rotate_transformer_test.cpp
  src/impl/transform/pca_transformer_test.cpp
  src/impl/transform/random_orthogonal_transformer_test.cpp
  src/io/basic_io_test.h
  src/quantization/product_quantization/pq_fastscan_quantizer_test.cpp
  src/quantization/quantizer_test.h
  src/storage/serialization_template_test.h
  tests/fixtures/fixtures.h
  tests/test_ivf.cpp
Labels: kind/improvement, size/L, module/testing, version/0.16

#993 eliminate the effect of data size on the efsearch threshold
  src/algorithm/hgraph.cpp
  src/index/hnsw.cpp
Labels: kind/improvement, size/M, version/0.16

#988 support filter search when supporting duplicate data
  src/algorithm/hgraph.cpp
  src/impl/basic_searcher.cpp
  src/label_table.h
  tests/fixtures/fixtures.h
  tests/fixtures/test_dataset.cpp
  tests/fixtures/test_dataset.h
  tests/fixtures/test_dataset_pool.cpp
  tests/fixtures/test_dataset_pool.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
Labels: kind/improvement, size/L, module/testing, version/0.16

#1010 add data export for heap
  src/impl/heap/distance_heap.h
  src/impl/heap/distance_heap_test.cpp
  src/impl/heap/memmove_heap.h
  src/impl/heap/standard_heap.cpp
  src/impl/heap/standard_heap.h
Labels: kind/improvement, size/M, version/0.16

#1007 cherry-pick #880 to 0.15 (improve compressed graph in compression ratio)
  src/data_cell/compressed_graph_datacell.cpp
  src/data_cell/compressed_graph_datacell.h
  src/impl/elias_fano_encoder.cpp
  src/impl/elias_fano_encoder.h
  src/impl/elias_fano_encoder_test.cpp
Labels: kind/improvement, size/M, version/0.15

#1009 Support concurrent in SINDI
  src/algorithm/sindi/sindi.cpp
  src/algorithm/sindi/sindi.h
  src/algorithm/sindi/sindi_test.cpp
  src/data_cell/sparse_term_datacell.cpp
  tests/test_index.cpp
  tests/test_index.h
  tests/test_sindi.cpp
Labels: kind/improvement, size/L, module/testing, version/0.16

#923 add remove for brute force
  src/algorithm/brute_force.cpp
  src/algorithm/brute_force.h
  tests/test_brute_force.cpp
Labels: kind/improvement, size/L, module/testing, version/0.16

#1008 add meta information for sindi
  src/algorithm/sindi/sindi.cpp
  src/data_cell/sparse_term_datacell.cpp
  src/data_cell/sparse_term_datacell.h
  src/data_cell/sparse_term_datacell_test.cpp
Labels: kind/improvement, size/M, version/0.16

#961 support update extra info on HGraph
  include/vsag/index.h
  include/vsag/index_features.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/inner_index_interface.h
  src/algorithm/inner_index_interface_test.cpp
  src/index/index_impl.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
  tests/test_index.h
  tests/test_simple_index.cpp
Labels: kind/feature, size/L, module/testing, module/api, version/0.16

#1012 refactor heap merge on ivf parallel search
  src/algorithm/ivf.cpp
Labels: kind/improvement, size/S, version/0.17

#1016 optimize IteratorFilterContext bitmap memory usage
  src/index/iterator_filter.cpp
  src/index/iterator_filter.h
  src/index/iterator_filter_test.cpp
Labels: kind/improvement, size/M, version/0.15

#1022 fix label_remap size serialize
  src/algorithm/hgraph.cpp
Labels: size/XS, needs-cherry-pick-release-0.15, needs-cherry-pick-release-0.16

#1024 add more tag index check on compatibility
  scripts/check_compatibility.sh
Labels: kind/improvement, size/XS, version/0.17

#1005 add benchmark parameters of popular datasets
  benchs/README.md
  benchs/datasets/sift-90.yml
  benchs/indexes/hgraph-90.yml
  benchs/indexes/hgraph-95.yml
  benchs/indexes/hgraph-99.yml
  tools/eval/case/build_eval_case.cpp
  tools/eval/case/search_eval_case.cpp
  tools/eval/case/search_eval_case.h
Labels: kind/improvement, size/L, module/tools, version/0.17

#1037 increase beam width during reordering
  src/impl/reorder.cpp
  tests/fixtures/test_reader.h
  tests/test_hgraph.cpp
Labels: kind/improvement, size/S, module/testing, version/0.17, needs-cherry-pick-release-0.16

#1032 [skip ci] update document of hgraph
  docs/hgraph_params.md
Labels: kind/documentation, size/S, version/0.17

#1038 update perf.yml for COHERE
  benchs/indexes/hgraph-90.yml
  benchs/indexes/hgraph-95.yml
  benchs/indexes/hgraph-99.yml
Labels: kind/documentation, size/S, version/0.17

#1027 add overtime check on search
  docs/ivf.md
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph_parameter.cpp
  src/algorithm/hgraph_parameter.h
  src/algorithm/ivf.cpp
  src/algorithm/ivf_parameter.h
  src/impl/basic_searcher.cpp
  src/impl/basic_searcher.h
  src/impl/inner_search_param.h
  src/inner_string_params.h
  src/utils/timer.cpp
  src/utils/timer.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
  tests/test_index.h
  tests/test_ivf.cpp
Labels: kind/feature, size/L, module/testing, version/0.17

#1023 add file remove check on disk io type
  src/io/CMakeLists.txt
  src/io/async_io.cpp
  src/io/async_io.h
  src/io/async_io_test.cpp
  src/io/basic_io_test.h
  src/io/buffer_io.cpp
  src/io/buffer_io.h
  src/io/buffer_io_test.cpp
  src/io/mmap_io.cpp
  src/io/mmap_io.h
  src/io/mmap_io_test.cpp
Labels: kind/improvement, size/L, version/0.17

#1042 reduce memory on fast_bitset
  src/impl/bitset/fast_bitset.cpp
  src/impl/bitset/fast_bitset.h
Labels: kind/improvement, size/S, version/0.17

#1044 fix incorrect CXX ABI in binary distribution
  CMakeLists.txt
  Makefile
  docker/Dockerfile.dist_cxx11_x86
  docker/Dockerfile.dist_pre_cxx11_x86
  scripts/release/check-cpp-abi.sh
  scripts/release/dist.sh
Labels: kind/bug, size/L, needs-cherry-pick-release-0.14, needs-cherry-pick-release-0.15, version/0.17, needs-cherry-pick-release-0.16

#1067 replace Vector with raw pointer on bitset
  src/impl/bitset/computable_bitset.h
  src/impl/bitset/fast_bitset.cpp
  src/impl/bitset/fast_bitset.h
  src/impl/bitset/sparse_bitset.h
Labels: kind/improvement, size/L, version/0.17

#1063 support store raw vector on HGraph
  include/vsag/constants.h
  src/algorithm/brute_force.cpp
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/hgraph_parameter.cpp
  src/algorithm/hgraph_parameter.h
  src/constants.cpp
  src/inner_string_params.h
Labels: kind/improvement, size/L, version/0.17

#1045 support analyze HGraph by searching
  include/vsag/index.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/inner_index_interface.h
  src/index/index_impl.h
  tests/test_hgraph.cpp
  tools/analyze_index/AnalysisReportInterpretation.md
  tools/analyze_index/analyze_index.cpp
Labels: kind/improvement, size/L, module/tools, module/testing, module/api, version/0.17

#1056 support tombstone recovery in hnsw
  src/algorithm/hnswlib/algorithm_interface.h
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
  src/index/hnsw.cpp
  tests/test_index_old.cpp
  tests/test_multi_thread.cpp
Labels: kind/feature, size/L, module/testing, version/0.17

#1083 fix(hgraph): fix HGraph deserialization failure
  src/algorithm/hgraph.cpp
  tests/test_hgraph.cpp
Labels: kind/bug, size/XS, module/testing, version/0.17, needs-cherry-pick-release-0.16

#1089 refactor(quantizer): optimize quantizer's compute
  src/data_cell/sparse_vector_datacell.inl
  src/quantization/CMakeLists.txt
  src/quantization/computer.h
  src/quantization/computer_interface.h
  src/quantization/product_quantization/pq_fastscan_quantizer_test.cpp
  src/quantization/quantizer.h
  src/quantization/quantizer_interface.cpp
  src/quantization/quantizer_interface.h
  src/quantization/quantizer_test.h
  src/quantization/transform_quantization/transform_quantizer.cpp
  src/quantization/transform_quantization/transform_quantizer.h
  src/quantization/transform_quantization/transform_quantizer_test.cpp
Labels: kind/improvement, size/XXL, version/0.17

#1082 feat(reader): add the MultRead method to the reader interface
  include/vsag/readerset.h
  mockimpl/vsag/factory.cpp
  src/io/reader_io.cpp
  src/reader.cpp
Labels: kind/improvement, size/L, version/0.17, needs-cherry-pick-release-0.16
