Repository antgroup/vsag, pull requests merged in 2025-07, with the labels that each got.

#875 fix different size operator for fast bitset
  src/impl/bitset/fast_bitset.cpp
Labels: kind/bug, size/M, version/0.16, needs-cherry-pick-release-0.15

#882 skip invalid rabitq configuration test
  tests/test_hgraph.cpp
Labels: kind/bug, size/L, module/testing, version/0.16

#888 fix antlr4 compilation issue
  extern/antlr4/antlr4.cmake
Labels: kind/bug, size/XS, needs-cherry-pick-release-0.15

#891 fix coredump in hgraph when using empty parameter (cp 0.15)
  src/algorithm/hgraph.cpp
  tests/test_hgraph.cpp
Labels: size/M, module/testing

#893 fix bug on not operator of fast bitset
  src/impl/bitset/fast_bitset.cpp
  src/impl/bitset/fast_bitset.h
  src/impl/bitset/fast_bitset_test.cpp
Labels: kind/bug, size/XL, version/0.16, needs-cherry-pick-release-0.15

#899 add attr type map for expr
  src/attr/attr_type_schema.cpp
  src/attr/attr_type_schema.h
  src/attr/attr_type_schema_test.cpp
  src/data_cell/attribute_bucket_inverted_datacell.cpp
  src/data_cell/attribute_inverted_datacell.cpp
  src/data_cell/attribute_inverted_interface.h
Labels: kind/improvement, size/L, version/0.16

#896 optimize whitelistfilter's shared_ptr
  include/vsag/bitset.h
  src/attr/executor/comparison_executor.cpp
  src/attr/executor/logical_executor.cpp
  src/impl/bitset/fast_bitset.cpp
  src/impl/bitset/fast_bitset.h
  src/impl/bitset/sparse_bitset.cpp
  src/impl/bitset/sparse_bitset.h
  src/impl/filter/white_list_filter.cpp
  src/impl/filter/white_list_filter.h
Labels: kind/improvement, size/M, version/0.16

#904 remove redundant immutable checks in deserialization
  src/index/index_impl.h
  src/index/index_impl_test.cpp
Labels: kind/bug, size/S, version/0.16, needs-cherry-pick-release-0.15

#900 remove file when use "disk io" type
  src/io/async_io.cpp
  src/io/async_io.h
  src/io/buffer_io.h
  src/io/mmap_io.h
Labels: kind/improvement, size/S, version/0.16

#910 use update on list executor
  src/attr/executor/integer_list_executor.cpp
  src/attr/executor/string_list_executor.cpp
Labels: kind/improvement, size/XS, version/0.16

#918 fix compatibility issues in diskann (cp 0.13)
  src/index/diskann.cpp
Labels: size/XS

#907 update str pipe list gramma
  extern/antlr4/antlr4.cmake
  extern/antlr4/fc/FC.interp
  extern/antlr4/fc/FC.tokens
  extern/antlr4/fc/FCBaseListener.cpp
  extern/antlr4/fc/FCBaseListener.h
  extern/antlr4/fc/FCBaseVisitor.cpp
  extern/antlr4/fc/FCBaseVisitor.h
  extern/antlr4/fc/FCLexer.cpp
  extern/antlr4/fc/FCLexer.h
  extern/antlr4/fc/FCLexer.interp
  extern/antlr4/fc/FCLexer.tokens
  extern/antlr4/fc/FCListener.cpp
  extern/antlr4/fc/FCListener.h
  extern/antlr4/fc/FCParser.cpp
  extern/antlr4/fc/FCParser.h
  extern/antlr4/fc/FCVisitor.cpp
  extern/antlr4/fc/FCVisitor.h
  src/algorithm/ivf.cpp
  src/attr/executor/integer_list_executor.cpp
  src/attr/expression_visitor.cpp
  src/attr/expression_visitor.h
  src/attr/grammar/FC.g4
  tests/test_fc_visitor.cpp
Labels: size/XL, module/testing, version/0.16

#928 improve converage
  src/data_cell/compressed_graph_datacell.cpp
  src/data_cell/compressed_graph_datacell_test.cpp
  src/data_cell/extra_info_datacell.h
  src/data_cell/extra_info_interface.h
  src/data_cell/extra_info_interface_test.cpp
  src/data_cell/flatten_datacell.h
  src/data_cell/flatten_interface.h
  src/data_cell/sparse_vector_datacell.h
Labels: kind/improvement, size/M

#892 support ip and cosine
  src/data_cell/flatten_datacell_test.cpp
  src/data_cell/flatten_interface.cpp
  src/quantization/quantizer_test.h
  src/quantization/rabitq_quantization/rabitq_quantizer.h
  src/quantization/rabitq_quantization/rabitq_quantizer_test.cpp
  src/simd/avx.cpp
  src/simd/avx2.cpp
  src/simd/avx512.cpp
  tests/test_hgraph.cpp
Labels: size/L, module/simd, module/testing

#919 add thread_pool for parallel build&search for IVF
  include/vsag/constants.h
  src/algorithm/ivf.cpp
  src/algorithm/ivf.h
  src/algorithm/ivf_parameter.cpp
  src/algorithm/ivf_parameter.h
  src/algorithm/ivf_parameter_test.cpp
  src/constants.cpp
  src/impl/basic_searcher.h
  src/inner_string_params.h
  tests/test_ivf.cpp
Labels: kind/feature, size/L, module/testing, version/0.16

#933 improve CI recall on ivf gno-imi test
  tests/test_ivf.cpp
Labels: kind/improvement, size/S, module/testing, version/0.16

#955 workflow trigger by tag v*.*.*
  .github/workflows/generate_old_version_index.yml
Labels: kind/improvement, size/XS, version/0.16

#958 split quantization implement
  src/parameter_test.h
  src/quantization/CMakeLists.txt
  src/quantization/fp32_quantizer.cpp
  src/quantization/fp32_quantizer.h
  src/quantization/product_quantization/pq_fastscan_quantizer.cpp
  src/quantization/product_quantization/pq_fastscan_quantizer.h
  src/quantization/product_quantization/pq_fastscan_quantizer_parameter_test.cpp
  src/quantization/product_quantization/product_quantizer.cpp
  src/quantization/product_quantization/product_quantizer.h
  src/quantization/product_quantization/product_quantizer_parameter_test.cpp
  src/quantization/quantizer.h
  src/quantization/rabitq_quantization/rabitq_quantizer.cpp
  src/quantization/rabitq_quantization/rabitq_quantizer.h
  src/quantization/rabitq_quantization/rabitq_quantizer_test.cpp
  src/quantization/scalar_quantization/bf16_quantizer.cpp
  src/quantization/scalar_quantization/bf16_quantizer.h
  src/quantization/scalar_quantization/fp16_quantizer.cpp
  src/quantization/scalar_quantization/fp16_quantizer.h
  src/quantization/scalar_quantization/sq4_quantizer.cpp
  src/quantization/scalar_quantization/sq4_quantizer.h
  src/quantization/scalar_quantization/sq4_uniform_quantizer.cpp
  src/quantization/scalar_quantization/sq4_uniform_quantizer.h
  src/quantization/scalar_quantization/sq4_uniform_quantizer_parameter_test.cpp
  src/quantization/scalar_quantization/sq8_quantizer.cpp
  src/quantization/scalar_quantization/sq8_quantizer.h
  src/quantization/scalar_quantization/sq8_uniform_quantizer.cpp
  src/quantization/scalar_quantization/sq8_uniform_quantizer.h
Labels: kind/improvement, size/XXL, version/0.16

#959 use buffer_stream_reader to speedup deserialize
  src/algorithm/brute_force.cpp
  src/algorithm/hgraph.cpp
  src/algorithm/ivf.cpp
  src/algorithm/pyramid.cpp
  src/storage/stream_reader.cpp
Labels: kind/improvement, size/M, version/0.16

#962 support concurrent add on ivf attribute
  src/algorithm/ivf.cpp
  src/data_cell/bucket_datacell.h
  src/data_cell/bucket_interface.h
Labels: kind/improvement, size/M, version/0.16

#978 fix Core dump occurs when running pqfs performance evaluation
  src/data_cell/flatten_interface.cpp
  src/quantization/quantizer_headers.h
Labels: kind/bug, size/XS, version/0.16, needs-cherry-pick-release-0.15

#971 sovle reducing recall caused by duplicate data in hgraph
  include/vsag/constants.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/hgraph_parameter.cpp
  src/algorithm/hgraph_parameter.h
  src/algorithm/hgraph_parameter_test.cpp
  src/constants.cpp
  src/impl/basic_searcher.cpp
  src/impl/basic_searcher.h
  src/inner_string_params.h
  src/label_table.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/improvement, size/L, module/testing, version/0.16

#987 mark in_memory to a constexpr value
  src/data_cell/extra_info_datacell.h
  src/data_cell/flatten_datacell.h
  src/data_cell/graph_datacell.h
  src/io/async_io.h
  src/io/async_io_test.cpp
  src/io/basic_io.h
  src/io/buffer_io.cpp
  src/io/buffer_io.h
  src/io/memory_block_io.h
  src/io/memory_io.h
  src/io/mmap_io.h
  src/io/reader_io.cpp
  src/io/reader_io.h
Labels: kind/improvement, size/L, version/0.16

#986 reduce attr bitset memory
  src/attr/multi_bitset_manager.cpp
  src/attr/multi_bitset_manager.h
Labels: kind/improvement, size/M, version/0.16

#967 add update attr with old values
  include/vsag/index.h
  src/algorithm/inner_index_interface.h
  src/algorithm/inner_index_interface_test.cpp
  src/algorithm/ivf.cpp
  src/algorithm/ivf.h
  src/attr/attr_value_map.h
  src/data_cell/attribute_bucket_inverted_datacell.cpp
  src/data_cell/attribute_bucket_inverted_datacell.h
  src/data_cell/attribute_inverted_interface.h
  src/index/index_impl.h
  tests/test_index.cpp
  tests/test_index.h
  tests/test_ivf.cpp
  tests/test_simple_index.cpp
Labels: kind/feature, size/L, module/testing, version/0.16

#984 refactor sindi parameter
  .github/perf-90.yml
  include/vsag/constants.h
  src/algorithm/sindi/sindi.cpp
  src/algorithm/sindi/sindi.h
  src/algorithm/sindi/sindi_parameter.cpp
  src/algorithm/sindi/sindi_parameter.h
  src/algorithm/sindi/sindi_parameter_test.cpp
  src/algorithm/sindi/sindi_test.cpp
  src/constants.cpp
  src/data_cell/sparse_term_datacell.cpp
  src/data_cell/sparse_term_datacell.h
  src/data_cell/sparse_term_datacell_test.cpp
  src/engine.cpp
  src/quantization/sparse_quantization/sparse_term_computer.h
  src/quantization/sparse_quantization/sparse_term_computer_test.cpp
Labels: kind/improvement, size/L, version/0.16
