Repository antgroup/vsag, pull requests merged in 2025-06, with the labels that each got.

#716 Search to add a separate allocator
  examples/cpp/313_feature_search_allocator.cpp
  examples/cpp/314_feature_hgraph_search_allocator.cpp
  examples/cpp/CMakeLists.txt
  include/vsag/index.h
  include/vsag/search_param.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/hnswlib/algorithm_interface.h
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
  src/algorithm/hnswlib/hnswalg_static.h
  src/algorithm/inner_index_interface.h
  src/data_cell/flatten_datacell.h
  src/data_cell/flatten_interface.h
  src/data_cell/sparse_vector_datacell.h
  src/impl/basic_searcher.cpp
  src/impl/basic_searcher.h
  src/index/hnsw.cpp
  src/index/hnsw.h
  src/index/index_impl.h
  src/index/iterator_filter.cpp
  src/index/iterator_filter.h
  tests/test_hgraph.cpp
  tests/test_hnsw_new.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/feature, size/XL, module/testing, version/0.15

#770 print memory usage detail in eval_performance for HGraph
  include/vsag/index.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/inner_index_interface.h
  src/data_cell/extra_info_interface.h
  src/data_cell/flatten_interface.h
  src/data_cell/graph_interface.h
  src/index/index_impl.h
  tests/test_hgraph.cpp
  tools/eval/case/build_eval_case.cpp
  tools/eval/case/search_eval_case.cpp
Labels: kind/improvement, size/L, module/tools, module/testing, version/0.15

#784 fix segment fault and recall degradation issues in compressed HGraph
  src/data_cell/compressed_graph_datacell.cpp
Labels: kind/bug, size/S, module/datacell

#775 add spdlog to the deps of mockimpl
  mockimpl/CMakeLists.txt
Labels: kind/bug, size/XS, version/0.15

#783 support mark-delete in Hgraph
  examples/cpp/303_feature_remove.cpp
  include/vsag/constants.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/constants.cpp
  src/data_cell/sparse_graph_datacell.cpp
  src/label_table.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/feature, size/L, module/testing, version/0.15

#786 [skip ci]add a link to RabitQ-Library in README
  README.md
Labels: kind/documentation, size/XS, version/0.15

#766 add attribute query interface
  include/vsag/search_request.h
  src/algorithm/inner_index_interface.cpp
  src/algorithm/inner_index_interface.h
  src/impl/bitset/computable_bitset.h
  src/impl/bitset/fast_bitset.h
  src/impl/bitset/sparse_bitset.h
  src/index/index_impl.h
Labels: kind/improvement, size/M, version/0.15

#788 improve coverage rate
  .github/workflows/coverage.yml
  src/algorithm/inner_index_interface.h
  src/algorithm/inner_index_interface_test.cpp
  src/algorithm/ivf_parameter_test.cpp
  tests/test_simple_index.cpp
Labels: kind/improvement, size/M, module/testing, version/0.15

#776 enable id map function for ivf merge
  src/algorithm/ivf.cpp
  src/label_table.cpp
  src/label_table.h
Labels: kind/improvement, size/S, version/0.15

#791 [skip ci] update Hgraph doc
  docs/hgraph_params.md
Labels: kind/documentation, size/M, version/0.15

#792 use specified commit of thread_pool instead of master branch
  extern/thread_pool/thread_pool.cmake
Labels: kind/bug, size/XS, version/0.15

#773 Add gramma expression define and expression visitor
  CMakeLists.txt
  extern/antlr4/antlr4.cmake
  extern/antlr4/fc/FC.interp
  extern/antlr4/fc/FC.tokens
  extern/antlr4/fc/FCBaseListener.cpp
  extern/antlr4/fc/FCBaseListener.h
  extern/antlr4/fc/FCBaseVisitor.cpp
  extern/antlr4/fc/FCBaseVisitor.h
  extern/antlr4/fc/FCLexer.cpp
  extern/antlr4/fc/FCLexer.h
  extern/antlr4/fc/FCLexer.interp
  extern/antlr4/fc/FCLexer.tokens
  extern/antlr4/fc/FCListener.cpp
  extern/antlr4/fc/FCListener.h
  extern/antlr4/fc/FCParser.cpp
  extern/antlr4/fc/FCParser.h
  extern/antlr4/fc/FCVisitor.cpp
  extern/antlr4/fc/FCVisitor.h
  src/CMakeLists.txt
  src/attr/expression.h
  src/attr/expression_visitor.h
  src/attr/grammar/FC.g4
  tests/test_fc_visitor.cpp
Labels: kind/feature, size/XXL, module/testing, version/0.15

#765 Support neon instructions acceleration on ARM
  .gitignore
  CMakeLists.txt
  cmake/CheckSIMDCompilerFlag.cmake
  src/simd/CMakeLists.txt
  src/simd/basic_func.cpp
  src/simd/basic_func.h
  src/simd/basic_func_test.cpp
  src/simd/bf16_simd.cpp
  src/simd/bf16_simd.h
  src/simd/bf16_simd_test.cpp
  src/simd/bit_simd.cpp
  src/simd/bit_simd.h
  src/simd/bit_simd_test.cpp
  src/simd/fp16_simd.cpp
  src/simd/fp16_simd.h
  src/simd/fp16_simd_test.cpp
  src/simd/fp32_simd.cpp
  src/simd/fp32_simd.h
  src/simd/fp32_simd_test.cpp
  src/simd/neon.cpp
  src/simd/normalize.cpp
  src/simd/normalize.h
  src/simd/normalize_test.cpp
  src/simd/pqfs_simd.cpp
  src/simd/pqfs_simd.h
  src/simd/pqfs_simd_test.cpp
  src/simd/rabitq_simd.cpp
  src/simd/rabitq_simd.h
  src/simd/rabitq_simd_test.cpp
  src/simd/simd.cpp
  src/simd/simd_status.h
  src/simd/sq4_simd.cpp
  src/simd/sq4_simd.h
  src/simd/sq4_simd_test.cpp
  src/simd/sq4_uniform_simd.cpp
  src/simd/sq4_uniform_simd.h
  src/simd/sq4_uniform_simd_test.cpp
  src/simd/sq8_simd.cpp
  src/simd/sq8_simd.h
  src/simd/sq8_simd_test.cpp
  src/simd/sq8_uniform_simd.cpp
  src/simd/sq8_uniform_simd.h
  src/simd/sq8_uniform_simd_test.cpp
  src/vsag.cpp
  tests/CMakeLists.txt
Labels: size/XXL, module/simd, module/testing, version/0.15

#798 add antlr4 into cache
  extern/antlr4/antlr4.cmake
Labels: kind/improvement, size/XS, version/0.15

#808 add block option to limit hgraph index size
  create_old_version_index.cpp
Labels: size/XS

#822 distinguish between memory usage during index build and search
  tools/eval/case/build_eval_case.cpp
  tools/eval/case/search_eval_case.cpp
  tools/eval/exporter/formatter_table.h
  tools/eval/monitor/memory_peak_monitor.cpp
  tools/eval/monitor/memory_peak_monitor.h
Labels: kind/improvement, size/M, module/tools, version/0.15

#826 update script for compatibility
  scripts/check_compatibility.sh
Labels: kind/improvement, size/XS, version/0.15

#827 unify the distance for uniform quantizer
  src/quantization/scalar_quantization/sq4_uniform_quantizer.h
  src/quantization/scalar_quantization/sq8_uniform_quantizer.h
Labels: size/S

#816 rabitq sq4 quer performance optimization
  CMakeLists.txt
  cmake/CheckSIMDCompilerFlag.cmake
  src/quantization/rabitq_quantization/rabitq_quantizer.h
  src/quantization/rabitq_quantization/rabitq_quantizer_test.cpp
  src/simd/CMakeLists.txt
  src/simd/avx512vpopcntdq.cpp
  src/simd/rabitq_simd.cpp
  src/simd/rabitq_simd.h
  src/simd/rabitq_simd_test.cpp
  src/simd/simd.cpp
  src/simd/simd_status.h
  src/utils/util_functions.h
  src/vsag.cpp
  tests/CMakeLists.txt
Labels: kind/improvement, size/XL, module/simd, module/testing, version/0.15

#829 bitset speedup
  src/attr/executor/integer_list_executor.cpp
  src/attr/executor/string_list_executor.cpp
  src/impl/bitset/bitset_test.cpp
  src/impl/bitset/computable_bitset.cpp
  src/impl/bitset/computable_bitset.h
  src/impl/bitset/fast_bitset.cpp
  src/impl/bitset/fast_bitset.h
  src/impl/bitset/fast_bitset_test.cpp
  src/impl/bitset/sparse_bitset.cpp
  src/impl/bitset/sparse_bitset.h
  src/impl/bitset/sparse_bitset_test.cpp
Labels: kind/improvement, size/L, version/0.15

#844 add spdlog into the dependencies of storage in cmake
  src/storage/CMakeLists.txt
Labels: kind/bug, size/XS

#835 optimize for simd
  src/simd/avx.cpp
  src/simd/avx2.cpp
  src/simd/avx512.cpp
  src/simd/generic.cpp
  src/simd/rabitq_simd.cpp
  src/simd/rabitq_simd.h
  src/simd/rabitq_simd_test.cpp
  src/simd/simd.h
  src/simd/sse.cpp
Labels: kind/improvement, size/XL, module/simd, version/0.16, needs-cherry-pick-release-0.15

#850 fix: include missing headerfile for type issues
  src/byte_buffer.h
Labels: kind/bug, size/XS, needs-cherry-pick-release-0.15

#834 attr datacell serialize and fastbit's bugfix
  src/algorithm/ivf.cpp
  src/attr/executor/executor.h
  src/attr_value_map.h
  src/data_cell/attribute_bucket_inverted_datacell.cpp
  src/data_cell/attribute_bucket_inverted_datacell_test.cpp
  src/data_cell/attribute_inverted_datacell.cpp
  src/data_cell/attribute_inverted_datacell_test.cpp
  src/data_cell/attribute_inverted_interface.h
  src/impl/bitset/fast_bitset.cpp
Labels: size/M, version/0.16, needs-cherry-pick-release-0.15

#854 support get num removed
  include/vsag/index.h
  src/algorithm/hgraph.h
  src/algorithm/inner_index_interface.h
  src/algorithm/inner_index_interface_test.cpp
  src/index/hnsw.cpp
  src/index/hnsw.h
  src/index/index_impl.h
  tests/test_index.cpp
  tests/test_index_old.cpp
Labels: kind/feature, size/M, module/testing

#780 support concurrent add in ivf
  src/algorithm/ivf.cpp
  src/algorithm/ivf_partition/gno_imi_partition.cpp
  src/algorithm/ivf_partition/gno_imi_partition.h
  src/algorithm/ivf_partition/ivf_nearest_partition.cpp
  src/algorithm/ivf_partition/ivf_nearest_partition.h
  src/algorithm/ivf_partition/ivf_partition_strategy.h
  src/data_cell/bucket_datacell.h
  tests/test_ivf.cpp
Labels: kind/improvement, size/L, module/testing, version/0.16, needs-cherry-pick-release-0.15
