Repository antgroup/vsag, pull requests merged in 2025-04, with the labels that each got.

#545 some simd optimize
  src/simd/avx512.cpp
Labels: kind/improvement, size/M, module/simd, version/0.14

#547 optimize prefetch operators
  src/impl/basic_searcher.cpp
  src/prefetch.h
  src/utils/visited_list.h
Labels: kind/improvement, size/S, version/0.14

#543 Support Hgraph Iterator Filter Search
  include/vsag/index.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/inner_index_interface.h
  src/impl/basic_searcher.cpp
  src/impl/basic_searcher.h
  src/index/index_impl.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
Labels: kind/feature, size/L, module/testing, version/0.14

#512 Supports getting the maximum and minimum label interface from the label
  include/vsag/index.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/hnswlib/algorithm_interface.h
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
  src/algorithm/hnswlib/hnswalg_static.h
  src/algorithm/inner_index_interface.h
  src/index/hnsw.h
  src/index/hnsw_test.cpp
  src/index/index_impl.h
  tests/test_hgraph.cpp
  tests/test_hnsw_new.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/feature, size/L, module/testing, version/0.14

#514 refactor hgraph to add point one by one
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/inner_index_interface.h
  src/data_cell/extra_info_datacell.h
  src/data_cell/extra_info_interface.h
  src/data_cell/flatten_datacell.h
  src/data_cell/graph_datacell.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
Labels: kind/improvement, size/L, module/testing, version/0.14

#555 reduce searcher allocator
  src/impl/basic_searcher.cpp
  src/impl/basic_searcher.h
Labels: kind/improvement, size/S, version/0.14

#549 optimiaze avx512 fp32 IP compute operator
  src/simd/avx512.cpp
Labels: kind/improvement, size/M, module/simd, version/0.14

#552 fix compile error for diskann while static link
  examples/cpp/CMakeLists.txt
  extern/diskann/DiskANN/src/logger.cpp
  src/vsag.cpp
Labels: kind/bug, size/S, version/0.14

#554 fix the issue where train_data_type_ is not initialized
  tools/eval/eval_dataset.cpp
Labels: kind/bug, size/M, module/tools, version/0.14

#559 fix coredump for searching empty HGraph index
  src/algorithm/hgraph.cpp
  src/algorithm/inner_index_interface.cpp
  src/algorithm/inner_index_interface.h
  src/algorithm/pyramid.cpp
  src/dataset_impl.cpp
  src/dataset_impl.h
  src/index/diskann.cpp
  tests/test_hgraph.cpp
  tests/test_hnsw_new.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/bug, size/L, module/testing, version/0.14

#532 remove the internal default resource creation while constructing engine
  examples/cpp/103_index_hgraph.cpp
  examples/cpp/203_custom_thread_pool.cpp
  examples/cpp/401_persistent_kv.cpp
  examples/cpp/402_persistent_streaming.cpp
  include/vsag/engine.h
  include/vsag/resource.h
  src/engine.cpp
  src/factory.cpp
  src/impl/odescent_graph_builder.cpp
  src/impl/odescent_graph_builder.h
  src/impl/odescent_graph_builder_test.cpp
  src/resource.cpp
  src/resource_owner_wrapper.h
  src/safe_allocator.h
  src/safe_thread_pool.h
  tests/test_engine.cpp
  tests/test_index.cpp
  tools/test_performance/main.cpp
Labels: size/L, module/tools, module/testing, version/0.14

#546 [skip ci]update README.md
  README.md
Labels: kind/improvement, size/S

#565 fix rabitq recall
  src/quantization/rabitq_quantization/rabitq_quantizer.h
Labels: kind/bug, size/XS, version/0.15, needs-cherry-pick-release-0.14

#566 speed up hgraph concurrent add
  src/algorithm/hgraph.cpp
  src/data_cell/flatten_datacell.h
  src/data_cell/flatten_interface.h
Labels: kind/improvement, size/S, version/0.15

#536 add elias-fano encoder
  src/impl/elias_fano_encoder.cpp
  src/impl/elias_fano_encoder.h
  src/impl/elias_fano_encoder_test.cpp
Labels: kind/feature, size/L, version/0.15

#560 optimize some simd operators
  src/simd/avx2.cpp
  src/simd/avx512.cpp
Labels: kind/improvement, size/L, module/simd, version/0.15

#575 add ci test for release branch
  .circleci/config.yml
  .github/workflows/asan_build_and_test.yml
  .github/workflows/asan_with_simd_option.yml
  .github/workflows/check_compatibility.yml
  .github/workflows/coverage.yml
  .github/workflows/format.yml
  .github/workflows/lint.yml
  .github/workflows/tsan_build_and_test.yml
Labels: kind/improvement, size/M, needs-cherry-pick-release-0.14

#556 opt some prefetch
  src/impl/basic_searcher.cpp
  src/impl/basic_searcher.h
  src/prefetch.h
Labels: kind/improvement, size/S, version/0.15

#577 fix coredump when searching empty index
  src/algorithm/inner_index_interface.cpp
  src/algorithm/inner_index_interface.h
  src/index/index_impl.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
Labels: kind/bug, size/M, module/testing, needs-cherry-pick-release-0.14

#573 fix interface KnnSearch with iter not adapted extra info
  src/algorithm/hgraph.cpp
  tests/test_hgraph.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/improvement, size/M, module/testing, version/0.14

#574 [main] fix interface KnnSearch with iter not adapted extra info
  src/algorithm/hgraph.cpp
  tests/test_hgraph.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: size/M, module/testing

#568 some typo fix
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg_static.h
  src/impl/odescent_graph_builder.cpp
  src/impl/pruning_strategy.cpp
  src/impl/pruning_strategy.h
  src/index/diskann.cpp
  src/index/diskann_test.cpp
  src/index/diskann_zparameters_test.cpp
  src/index/hnsw_test.cpp
  src/index/hnsw_zparameters_test.cpp
  src/utils/visited_list_test.cpp
  tools/eval/main.cpp
Labels: kind/improvement, size/L, module/tools, version/0.15

#533 store common attribute on inner index interface
  src/algorithm/brute_force.cpp
  src/algorithm/brute_force.h
  src/algorithm/brute_force_parameter.cpp
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/inner_index_interface.cpp
  src/algorithm/inner_index_interface.h
  src/algorithm/ivf.cpp
  src/algorithm/ivf.h
  src/algorithm/pyramid.cpp
  src/algorithm/pyramid.h
Labels: kind/improvement, size/L, version/0.15

#567 remove max_level_ in HGraph
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
Labels: size/S

#581 remove the dependency of bit
  src/io/memory_block_io.h
Labels: kind/improvement, size/XS, version/0.15

#582 fix bug due to narrow cast in HGraph
  src/algorithm/hgraph.cpp
Labels: kind/bug, size/XS, version/0.15

#583 speed up concurrent add on hgraph
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
Labels: kind/improvement, size/S, needs-cherry-pick-release-0.14

#572 hgraph support extra info filter
  include/vsag/constants.h
  include/vsag/filter.h
  include/vsag/index_features.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph_parameter.cpp
  src/algorithm/hgraph_parameter.h
  src/base_filter_functor.h
  src/constants.cpp
  src/data_cell/extra_info_datacell.h
  src/data_cell/extra_info_datacell_test.cpp
  src/data_cell/extra_info_interface.h
  src/data_cell/extra_info_interface_test.cpp
  tests/fixtures/test_dataset.cpp
  tests/fixtures/test_dataset.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/improvement, size/L, module/testing, version/0.15

#588 [bugfix][hgraph] fix core on large dataset build
  src/data_cell/extra_info_datacell.h
  src/data_cell/flatten_datacell.h
  src/data_cell/graph_datacell.h
Labels: kind/bug, size/XS, needs-cherry-pick-release-0.13, version/0.15, needs-cherry-pick-release-0.14

#593 hgraph support extra info filter
  include/vsag/constants.h
  include/vsag/filter.h
  include/vsag/index_features.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph_parameter.cpp
  src/algorithm/hgraph_parameter.h
  src/base_filter_functor.h
  src/constants.cpp
  src/data_cell/extra_info_datacell.h
  src/data_cell/extra_info_datacell_test.cpp
  src/data_cell/extra_info_interface.h
  src/data_cell/extra_info_interface_test.cpp
  tests/fixtures/test_dataset.cpp
  tests/fixtures/test_dataset.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/improvement, size/L, module/testing

#570 [skip ci]update README.md and DEVELOPMENT.md
  DEVELOPMENT.md
  README.md
Labels: kind/documentation, size/S, version/0.15

#590 add new version compatibility (0.14.x)
  scripts/check_compatibility.sh
Labels: kind/improvement, size/XS, version/0.15

#586 speed up build asan/tsan
  CMakeLists.txt
  Makefile
Labels: kind/improvement, size/XS

#585 add clone index implement
  include/vsag/index.h
  include/vsag/index_features.h
  src/algorithm/brute_force.cpp
  src/algorithm/brute_force.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/inner_index_interface.cpp
  src/algorithm/inner_index_interface.h
  src/algorithm/ivf.cpp
  src/algorithm/ivf.h
  src/algorithm/pyramid.cpp
  src/algorithm/pyramid.h
  src/algorithm/sparse_index.h
  src/index/index_impl.h
  tests/test_brute_force.cpp
  tests/test_hgraph.cpp
  tests/test_index.cpp
  tests/test_index.h
  tests/test_ivf.cpp
  tests/test_pyramid.cpp
Labels: kind/feature, size/L, module/testing, version/0.15

#571 remove some duplicate test
  mockimpl/CMakeLists.txt
  tests/test_hnsw.cpp
  tests/test_hnsw_new.cpp
Labels: kind/improvement, size/XL, module/testing, version/0.15

#594 fix abnormal latency statistics in eval_performance
  tools/eval/monitor/latency_monitor.cpp
  tools/eval/monitor/latency_monitor.h
Labels: kind/bug, size/S, module/tools, version/0.15

#598 fix get dist fail after delete
  src/index/hnsw.cpp
  tests/test_index_old.cpp
  tests/test_multi_thread.cpp
Labels: size/L, module/testing

#601 [skip ci] add benchmark for cohere and openai dataset
  .github/perf-90.yml
  .github/perf-95.yml
  .github/perf-99.yml
Labels: kind/improvement, size/M, version/0.15

#602 fix resize bug on hgraph concurrent add
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
Labels: kind/bug, size/M, needs-cherry-pick-release-0.14

#600 fix test hgraph
  tests/test_hgraph.cpp
Labels: size/XS, module/testing

#599 add export model & hgraph implement
  include/vsag/index.h
  include/vsag/index_features.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/inner_index_interface.h
  src/data_cell/flatten_datacell.h
  src/data_cell/flatten_interface.h
  src/data_cell/sparse_vector_datacell.h
  src/index/index_impl.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/feature, size/L, module/testing, version/0.15

#608 add train interface for index
  include/vsag/index.h
  src/algorithm/brute_force.cpp
  src/algorithm/brute_force.h
  src/algorithm/ivf.cpp
  src/algorithm/ivf.h
  src/index/index_impl.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: kind/feature, size/L, module/testing, version/0.15

#605 Support Index Clone
  examples/cpp/309_feature_clone.cpp
  examples/cpp/CMakeLists.txt
Labels: kind/feature, size/L, version/0.15

#508 use hgraph route for ivf
  src/algorithm/ivf_partition/ivf_nearest_partition.cpp
  src/algorithm/ivf_partition/ivf_nearest_partition_test.cpp
Labels: kind/improvement, size/M, module/testing, version/0.15

#628 add old version (v0.13.0_hnsw)
  v0.13.0_hnsw.index
  v0.13.0_hnsw_build.json
  v0.13.0_hnsw_search.json
Labels: size/S

#621 adjust openblas buffersize
  extern/openblas/openblas.cmake
Labels: size/XS

#614 improve coverage rate
  tests/test_simple_index.cpp
Labels: kind/improvement, size/XS, module/testing

#618 implement of IVF's export model
  src/algorithm/ivf.cpp
  src/algorithm/ivf.h
  src/algorithm/ivf_partition/ivf_partition_strategy.h
  src/data_cell/bucket_datacell.h
  src/data_cell/bucket_interface.h
  tests/test_index.cpp
  tests/test_ivf.cpp
Labels: kind/improvement, size/L, module/testing, version/0.15

#625 enable hgraph to use an externally provided thread pool
  src/algorithm/hgraph.cpp
Labels: kind/improvement, size/XS, version/0.15

#617 add curl to vsag develop dependencies
  .github/workflows/asan_build_and_test.yml
  DEVELOPMENT.md
  docker/Dockerfile.x86
  scripts/deps/install_deps_centos.sh
  scripts/deps/install_deps_ubuntu.sh
Labels: kind/improvement, size/S, version/0.15

#632 speed up calculate batch distance by ids
  src/algorithm/hgraph.cpp
Labels: kind/improvement, version/0.15, needs-cherry-pick-release-0.14

#643 update ci dockerfile
  docker/Dockerfile.x86
  scripts/deps/install_deps_centos.sh
  scripts/deps/install_deps_ubuntu.sh
Labels: kind/improvement, size/XS

#639 [skip ci]update binary distribution script
  scripts/release/dist.sh
Labels: kind/improvement, size/M, version/0.15, needs-cherry-pick-release-0.14

#638 fix openblas arm compile fail
  extern/openblas/openblas.cmake
Labels: kind/bug, size/XS, needs-cherry-pick-release-0.14

#640 speed up async io test on hgraph
  tests/test_hgraph.cpp
Labels: kind/improvement, size/S, module/testing, version/0.15

#635 avoid auto cancel on main branch ci test
  .github/workflows/asan_build_and_test.yml
  .github/workflows/asan_with_simd_option.yml
  .github/workflows/check_compatibility.yml
  .github/workflows/coverage.yml
  .github/workflows/lint.yml
  .github/workflows/tsan_build_and_test.yml
Labels: kind/improvement, size/S, version/0.15

#633 Support Export Model
  examples/cpp/310_feature_export_model.cpp
  examples/cpp/CMakeLists.txt
Labels: kind/feature, size/L, version/0.15

#626 introduce ProductQuantizer
  src/quantization/product_quantization/product_quantizer.h
  src/quantization/product_quantization/product_quantizer_test.cpp
  src/quantization/quantizer_headers.h
  src/quantization/quantizer_test.h
Labels: kind/feature, size/XL, version/0.15

#647 Update lint.yml to revert the changes
  .github/workflows/lint.yml
Labels: kind/bug, size/XS

#652 remove force in memory for disk io type hgraph
  src/algorithm/hgraph.cpp
  src/data_cell/extra_info_datacell.h
  src/data_cell/flatten_datacell.h
  src/data_cell/flatten_interface.h
  src/data_cell/sparse_vector_datacell.h
  tests/test_hgraph.cpp
Labels: kind/improvement, size/L, module/testing, version/0.15

#648 enable build_thread_count on hgraph
  src/algorithm/hgraph.cpp
Labels: kind/improvement, size/XS, version/0.15

#651 add more examples
  examples/cpp/306_feature_calculate_distance_by_id.cpp
  examples/cpp/307_feature_check_features.cpp
  examples/cpp/308_feature_estimate_memory.cpp
  examples/cpp/CMakeLists.txt
Labels: kind/improvement, size/L, version/0.15

#646 implement pq for hgraph
  include/vsag/constants.h
  src/algorithm/hgraph.cpp
  src/constants.cpp
  src/data_cell/bucket_interface.cpp
  src/data_cell/flatten_interface.cpp
  src/quantization/quantizer_parameter.cpp
  tests/test_hgraph.cpp
  tests/test_ivf.cpp
Labels: kind/feature, size/M, module/testing, version/0.15

#624 fix compatibility of hnsw
  scripts/check_compatibility.sh
  src/algorithm/hnswlib/hnswalg.cpp
Labels: kind/bug, size/M, needs-cherry-pick-release-0.13, version/0.15, needs-cherry-pick-release-0.14
