Repository antgroup/vsag, pull requests merged in 2025-03, with the labels that each got.

#441 support cal batch distance by id for hgraph
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  tests/test_hgraph.cpp
Labels: kind/improvement, size/M, module/testing, version/0.14

#457 speed up functests for ci
  .github/workflows/asan_build_and_test.yml
  .github/workflows/coverage.yml
  .github/workflows/lint.yml
  .github/workflows/performance.yml
  scripts/test_parallel_by_name.sh
Labels: kind/improvement, size/M, version/0.14

#461 [skip ci]disable performance check in pull request
  .github/workflows/performance.yml
  scripts/perf_reports/dingding.py
Labels: kind/improvement, size/XS

#450 fix bug in LocalFileReader when use async io in DiskANN
  extern/diskann/DiskANN/src/pq.cpp
  src/factory.cpp
  src/factory_test.cpp
  tests/test_diskann.cpp
Labels: kind/bug, size/L, module/testing

#472 fix direct io asan bug
  src/io/async_io.h
  src/io/direct_io_object.h
Labels: kind/bug, size/L

#462 [skip ci]update ci image refresh condition
  .github/workflows/update-ci-image.yml
Labels: kind/improvement, size/XS

#443 add different simd operator test for github action
  .github/workflows/asan_with_simd_option.yml
  Makefile
Labels: kind/improvement, size/L, version/0.14

#469 introduce CreateFastDataset
  src/algorithm/hgraph.cpp
  src/index/brute_force.cpp
  src/index/hnsw.cpp
  src/utils/util_functions.cpp
  src/utils/util_functions.h
Labels: kind/improvement, size/M

#474 [skip ci]support fix lint command
  .clang-tidy
  Makefile
Labels: size/S

#458 fix clang 13 compile error
  CMakeLists.txt
  src/index/diskann.h
Labels: kind/bug, size/S, version/0.14

#478 fix ef search bug on hgraph
  src/algorithm/hgraph.cpp
Labels: kind/bug, size/XS, version/0.14, needs-cherry-pick-release-0.13

#476 speed up cluster
  src/impl/kmeans_cluster.cpp
Labels: kind/improvement, size/M, version/0.14

#471 use using instead of typedef
  extern/diskann/DiskANN/src/distance.cpp
  extern/diskann/DiskANN/src/pq.cpp
  src/algorithm/hnswlib/hnswalg.h
  src/algorithm/hnswlib/space_ip.h
  src/algorithm/hnswlib/space_l2.h
  src/simd/basic_func.cpp
  src/simd/basic_func.h
  src/simd/simd.cpp
  src/simd/simd.h
  src/simd/simd_test.cpp
Labels: kind/improvement, size/L, module/simd, version/0.14

#483 fix tool eval_performance output nothing without exporters setting
  tools/eval/eval_template.yaml
  tools/eval/main.cpp
Labels: kind/bug, size/XS, module/tools

#487 add compatibility check
  .github/workflows/check_compatibility.yml
  scripts/check_compatibility.sh
  tools/CMakeLists.txt
  tools/check_compatibility/CMakeLists.txt
  tools/check_compatibility/check_compatibility.cpp
Labels: kind/improvement, size/L, module/tools

#488 disable simd ci when no changes on simd/
  .github/workflows/asan_with_simd_option.yml
Labels: kind/improvement, size/XS

#463 use searcher on HGraph
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/impl/basic_searcher.cpp
  src/impl/basic_searcher.h
  src/index/diskann.h
  src/index/pyramid.h
  tests/test_index.cpp
Labels: kind/improvement, size/L, module/testing, version/0.14

#495 fix compile bug in avx512 about fp16 and bf16
  src/simd/avx512.cpp
Labels: size/S, module/simd

#492 use distanceHeap instead MaxHeap on bruteforce
  src/index/brute_force.cpp
  src/utils/distance_heap.h
Labels: kind/improvement, size/M, version/0.14

#490 refactor some param, move bruteforce to algorithm
  .circleci/config.yml
  include/vsag/constants.h
  src/CMakeLists.txt
  src/algorithm/brute_force.cpp
  src/algorithm/brute_force.h
  src/algorithm/brute_force_parameter.cpp
  src/algorithm/brute_force_parameter.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph_parameter.cpp
  src/algorithm/hgraph_parameter.h
  src/algorithm/hnswlib/hnswalg.cpp
  src/algorithm/hnswlib/hnswalg.h
  src/algorithm/ivf.cpp
  src/algorithm/ivf.h
  src/algorithm/ivf_parameter_test.cpp
  src/algorithm/ivf_partition/ivf_nearest_classify_test.cpp
  src/algorithm/ivf_partition/ivf_nearest_partition.cpp
  src/algorithm/ivf_partition/ivf_nearest_partition.h
  src/algorithm/ivf_partition/ivf_partition_strategy.h
  src/constants.cpp
  src/engine.cpp
  src/impl/basic_searcher.cpp
  src/impl/basic_searcher.h
  src/index/hgraph_index_zparameters.cpp
  src/index/hgraph_index_zparameters.h
  src/quantization/fp32_quantizer.h
  src/quantization/scalar_quantization/bf16_quantizer.h
  src/quantization/scalar_quantization/fp16_quantizer.h
  src/quantization/scalar_quantization/sq4_quantizer.h
  src/quantization/scalar_quantization/sq8_quantizer.h
Labels: kind/improvement, size/L, version/0.14

#455 ensure thread-safe reading and writing for pyramid
  src/data_cell/flatten_datacell.h
  src/data_cell/flatten_interface.h
  src/index/pyramid.cpp
  src/index/pyramid.h
  tests/test_index.cpp
  tests/test_pyramid.cpp
Labels: kind/improvement, size/L, module/testing, version/0.14

#501 remove unnecessary code for filter
  src/base_filter_functor.h
Labels: size/S, version/0.14

#499 optimize filter in searcher
  src/impl/basic_searcher.cpp
  src/impl/basic_searcher.h
Labels: kind/improvement, size/S, version/0.14

#467 support rabitq in Hgraph
  src/algorithm/hgraph.cpp
  src/data_cell/flatten_interface.cpp
  src/impl/random_orthogonal_matrix.cpp
  src/impl/random_orthogonal_matrix.h
  src/impl/random_orthogonal_matrix_test.cpp
  src/inner_string_params.h
  src/quantization/quantizer_headers.h
  src/quantization/quantizer_parameter.cpp
  src/quantization/quantizer_test.h
  src/quantization/rabitq_quantization/rabitq_quantizer.h
  src/quantization/rabitq_quantization/rabitq_quantizer_test.cpp
  src/simd/generic.cpp
  src/simd/normalize.cpp
  src/simd/normalize.h
  tests/fixtures/fixtures.cpp
  tests/fixtures/fixtures.h
  tests/test_hgraph.cpp
Labels: size/L, module/simd, module/tools, module/testing, version/0.14

#497 add tsan pipeline
  .github/workflows/tsan_build_and_test.yml
  src/algorithm/hnswlib/hnswalg.cpp
  tests/test_brute_force.cpp
  tests/test_hgraph.cpp
  tests/test_hnsw_new.cpp
  tests/test_ivf.cpp
  tests/test_multi_thread.cpp
Labels: size/M, module/testing, version/0.14

#503 replace progschj::ThreadPool in hgraph
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
Labels: kind/improvement, size/S, version/0.14

#493 simplify the feature test for index
  src/index/diskann.cpp
  src/index/diskann.h
  src/index/pyramid.cpp
  src/index/pyramid.h
  tests/test_brute_force.cpp
  tests/test_hgraph.cpp
  tests/test_index.cpp
Labels: kind/improvement, size/L, module/testing, version/0.14

#500 use inner_index for ivf router
  src/algorithm/inner_index_interface.h
  src/algorithm/ivf.cpp
  src/algorithm/ivf_partition/ivf_nearest_partition.cpp
  src/algorithm/ivf_partition/ivf_nearest_partition.h
  src/algorithm/ivf_partition/ivf_nearest_partition_test.cpp
  src/algorithm/ivf_partition/ivf_partition_strategy.h
Labels: kind/improvement, size/L, version/0.14

#505 Support IVF Index
  examples/cpp/106_index_ivf.cpp
  examples/cpp/CMakeLists.txt
  tests/test_brute_force.cpp
  tests/test_hgraph.cpp
Labels: kind/feature, size/L, module/testing, version/0.14

#498 add ignore_reorder config to drop high_precise codes
  include/vsag/constants.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/hgraph_parameter.cpp
  src/algorithm/hgraph_parameter.h
  src/constants.cpp
  src/inner_string_params.h
  tests/test_hgraph.cpp
Labels: kind/improvement, size/M, module/testing, version/0.14

#491 support sparse index
  include/vsag/constants.h
  src/algorithm/sparse_index.cpp
  src/algorithm/sparse_index.h
  src/algorithm/sparse_index_parameters.cpp
  src/algorithm/sparse_index_parameters.h
  src/common.h
  src/constants.cpp
  src/dataset_impl_test.cpp
  src/engine.cpp
  src/index/pyramid.cpp
  src/inner_string_params.h
  tests/fixtures/fixtures.cpp
  tests/fixtures/fixtures.h
  tests/fixtures/test_dataset.cpp
  tests/fixtures/test_dataset.h
  tests/fixtures/test_dataset_pool.cpp
  tests/fixtures/test_dataset_pool.h
  tests/test_index.cpp
  tests/test_sparse_index.cpp
  tools/eval/case/build_eval_case.cpp
  tools/eval/case/search_eval_case.cpp
  tools/eval/common.h
  tools/eval/eval_dataset.cpp
  tools/eval/eval_dataset.h
Labels: size/XL, module/tools, module/testing

#518 add hdf5 files' attribute existence check before opening
  tools/eval/eval_dataset.cpp
Labels: kind/bug, size/S, module/tools

#502 introduce random train for ivf router
  include/vsag/constants.h
  src/algorithm/ivf.cpp
  src/algorithm/ivf_parameter.cpp
  src/algorithm/ivf_parameter.h
  src/algorithm/ivf_parameter_test.cpp
  src/algorithm/ivf_partition/ivf_nearest_partition.cpp
  src/constants.cpp
  src/inner_string_params.h
  src/utils/util_functions.cpp
  src/utils/util_functions.h
  tests/test_ivf.cpp
Labels: kind/improvement, size/M, module/testing, version/0.14

#511 skip threshold Calculation method
  src/algorithm/hnswlib/hnswalg.cpp
  src/impl/basic_searcher.cpp
Labels: size/XS

#486 hgraph support extra info
  include/vsag/constants.h
  include/vsag/dataset.h
  src/algorithm/hgraph.cpp
  src/algorithm/hgraph.h
  src/algorithm/hgraph_parameter.cpp
  src/algorithm/hgraph_parameter.h
  src/constants.cpp
  src/data_cell/extra_info_datacell.h
  src/data_cell/extra_info_datacell_parameter.cpp
  src/data_cell/extra_info_datacell_parameter.h
  src/data_cell/extra_info_datacell_test.cpp
  src/data_cell/extra_info_interface.cpp
  src/data_cell/extra_info_interface.h
  src/data_cell/extra_info_interface_test.cpp
  src/data_cell/extra_info_interface_test.h
  src/dataset_impl.h
  src/inner_string_params.h
  src/io/memory_block_io_parameter.cpp
  tests/fixtures/fixtures.cpp
  tests/fixtures/fixtures.h
  tests/fixtures/test_dataset.cpp
  tests/fixtures/test_dataset.h
  tests/fixtures/test_dataset_pool.cpp
  tests/fixtures/test_dataset_pool.h
  tests/test_hgraph.cpp
  tests/test_index.cpp
  tests/test_index.h
Labels: size/XXL, module/testing, version/0.14

#520 refactor some recall test on random dataset
  src/algorithm/brute_force.h
  src/algorithm/ivf.cpp
  src/data_cell/bucket_interface.cpp
  tests/test_brute_force.cpp
  tests/test_ivf.cpp
Labels: kind/improvement, size/M, module/testing, version/0.14

#521 remove unused code
  src/data_cell/graph_datacell.h
  src/data_cell/graph_interface.cpp
Labels: size/M

#507 support simd of rabitq-fp32
  src/quantization/rabitq_quantization/rabitq_quantizer.h
  src/simd/avx.cpp
  src/simd/avx2.cpp
  src/simd/avx512.cpp
  src/simd/generic.cpp
  src/simd/rabitq_simd.cpp
  src/simd/rabitq_simd.h
  src/simd/rabitq_simd_test.cpp
  src/simd/simd.h
  src/simd/sse.cpp
Labels: size/L, module/simd

#519 refactor pyramid and add an example
  examples/cpp/107_index_pyramid.cpp
  examples/cpp/CMakeLists.txt
  src/algorithm/pyramid.cpp
  src/algorithm/pyramid.h
  src/algorithm/pyramid_zparameters.cpp
  src/algorithm/pyramid_zparameters.h
  src/algorithm/pyramid_zparameters_test.cpp
  src/engine.cpp
  src/index/pyramid.h
  tests/test_index.cpp
  tests/test_pyramid.cpp
Labels: kind/improvement, size/XL, module/testing, version/0.14

#489 support multi-threading in eval_performance
  .github/perf-90.yml
  .github/perf-95.yml
  .github/perf-99.yml
  tools/eval/CMakeLists.txt
  tools/eval/case/search_eval_case.cpp
  tools/eval/eval_config.cpp
  tools/eval/eval_config.h
  tools/eval/eval_job.h
  tools/eval/eval_template.yaml
  tools/eval/main.cpp
  tools/eval/monitor/latency_monitor.cpp
  tools/eval/monitor/memory_peak_monitor.cpp
  tools/eval/monitor/monitor.h
  tools/eval/monitor/recall_monitor.cpp
Labels: kind/improvement, size/L, module/tools

#504 calculate recall by distance in test_performance
  tools/test_performance/main.cpp
Labels: kind/improvement, size/M, module/tools

#529 Support PCA for rabitq
  include/vsag/constants.h
  src/algorithm/hgraph.cpp
  src/constants.cpp
  src/impl/principal_component_analysis.cpp
  src/impl/principal_component_analysis.h
  src/impl/principal_component_analysis_test.cpp
  src/inner_string_params.h
  src/quantization/rabitq_quantization/rabitq_quantizer.h
  src/quantization/rabitq_quantization/rabitq_quantizer_parameter.cpp
  src/quantization/rabitq_quantization/rabitq_quantizer_parameter.h
  src/quantization/rabitq_quantization/rabitq_quantizer_parameter_test.cpp
  src/quantization/rabitq_quantization/rabitq_quantizer_test.cpp
Labels: kind/feature, size/XL, version/0.14

#527 fix illegal instruction happened on rabitq
  extern/openblas/openblas.cmake
Labels: kind/bug, size/S, version/0.14

#538 update flatten datacell prefetch length
  src/data_cell/flatten_datacell.h
Labels: kind/bug, size/XS, version/0.14

#515 add iter filter context interface
  include/vsag/iterator_context.h
  src/index/iterator_filter.cpp
  src/index/iterator_filter.h
  src/index/iterator_filter_test.cpp
Labels: size/L, version/0.14

#542 fix compile error in TestGetExtraInfoById
  tests/test_index.cpp
Labels: kind/bug, size/XS, module/testing, version/0.14
